const {run,summ,core}=require('./h.js');
const S=(x)=>{ if(x.err) return 'THROW '+(x.err.code||'')+' '+x.err.message.slice(0,150); const s=summ(x.r); const e=x.r.engine; return `n=${s.n} rr=${x.r.rulesResults.length} ${JSON.stringify(s.o)} ${s.n<6?s.ids.join(','):''} eng=${JSON.stringify({p:e.profile,pe:e.profileExcludes,w:e.wcagVersion,m:e.mappings,oi:e.optInRules})} ${x.warns.length?'WARN:'+x.warns.join('|').slice(0,200):''}`;};
const cases={
 rulesInc:{eo:{rules:{include:'img-alt-present'}}},
 rulesIncArr:{eo:{rules:{include:['img-alt-present','region']}}},
 rulesExc:{eo:{rules:{exclude:'img-alt-present'}}},
 tagsInc:{eo:{tags:{include:'wcag412'}}},
 testsInc:{eo:{tests:{include:'img-alt-present'}}},
 rulesStr:{eo:{rules:'img-alt-present'}},
 tagsArr:{eo:{tags:['wcag2a']}},
 eoTypo:{eo:{rules:{include:'img-alt-presnt'}}},
 eoTagTypo:{eo:{tags:{include:'wcag2aaa1'}}},
 runOnlyWins:{eo:{rules:{include:'region'}},ro:{includeRuleIds:['img-alt-present']}},
 runOnlyExclOnlyVsEoInc:{eo:{rules:{include:'region'}},ro:{excludeRuleIds:['img-alt-present']}},
 prof:{eo:{profile:'wcag22-aa'}},
 profUpper:{eo:{profile:'WCAG22-AA'}},
 profSpace:{eo:{profile:' section508 '}},
 prof508:{eo:{profile:'section508'}},
 profEn3:{eo:{profile:'en301549-v3.2.1'}},
 profEn4:{eo:{profile:'en301549-v4.1.1'}},
 profUnknown:{eo:{profile:'wcag99'}},
 profNum:{eo:{profile:5}},
 profEmpty:{eo:{profile:''}},
 profPlusInc:{eo:{profile:'wcag22-aa',rules:{include:'region'}}},
 profPlusExc:{eo:{profile:'wcag22-aa',rules:{exclude:'img-alt-present'}}},
 profPlusTagExc:{eo:{profile:'wcag22-aa',tags:{exclude:'wcag2a'}}},
 profPlusROexc:{eo:{profile:'wcag22-aa'},ro:{excludeRuleIds:['img-alt-present']}},
 profPlusROexcAndEoExc:{eo:{profile:'wcag22-aa',rules:{exclude:'button-name-present'}},ro:{excludeRuleIds:['img-alt-present']}},
 profPlusROinc:{eo:{profile:'wcag22-aa'},ro:['img-alt-present']},
 profPlusWcag21:{eo:{profile:'wcag22-aa',wcagVersion:'2.1'}},
 wcag20:{eo:{wcagVersion:'2.0'}},
 wcag21num:{eo:{wcagVersion:2.1}},
 wcag3:{eo:{wcagVersion:'3.0'}},
 wcag22sp:{eo:{wcagVersion:' 2.2 '}},
 optAll:{eo:{optInRules:'all'}},
 optBad:{eo:{optInRules:'nope'}},
 optTrue:{eo:{optInRules:true}},
 optNum:{eo:{optInRules:1}},
 map:{eo:{mappings:['en301549']}},
 mapVer:{eo:{mappings:'EN301549:v3.2.1'}},
 mapBad:{eo:{mappings:['iso','en301549:v9']}},
 mapObj:{eo:{mappings:{a:1}}},
 mapBoth:{eo:{mappings:'en301549, en301549:V3.2.1'}},
 inclModeOr:{eo:{rules:{include:'img-alt-present'},tags:{include:'best-practice'},includeMode:'OR'}},
};
for(const [k,c] of Object.entries(cases)) console.log(k.padEnd(22), S(run(c)));
