const C=[]; const add=(name,body,expect,extra={})=>C.push({name,body,expect,...extra});
add('read more labelledby self', '<h3 id=t1>Pricing</h3><a id=r1 href="/p" aria-labelledby="r1 t1">Read more</a>', {'label-in-name':'!fail','link-name-present':'pass'});
add('read more labelledby self+hidden', '<a id=r2 href="/p" aria-labelledby="r2 t2">Read more</a><span id=t2 hidden>about pricing</span>', {'label-in-name':'!fail'});
add('a role=none', '<a href="/" role=none>Home</a>', {'link-name-present':'!fail'});
add('button role=presentation', '<button role=presentation>Save</button>', {'button-name-present':'pass'});
add('input button role=none', '<input type=button role=none value=Go>', {'button-name-present':'pass'});
add('button role=switch', '<button role=switch aria-checked=false>Wifi</button>', {'button-name-present':'!fail'});
add('button role=tab', '<div role=tablist aria-label=t><button role=tab>Settings</button></div>', {'button-name-present':'!fail'});
add('button role=menuitem', '<div role=menu aria-label=m><button role=menuitem>Copy</button></div>', {'button-name-present':'!fail'});
add('button role=link', '<button role=link>Docs</button>', {'button-name-present':'!fail'});
add('dup label 2nd input', '<label for=dup>Email</label><input id=dup type=text><input id=dup type=text name=second>', {'form-control-programmatic-label-present':'fail'});
add('aria-hidden TRUE', '<span aria-hidden="TRUE">x</span>', {'aria-valid-attr-value':'!fail'});
add('aria-expanded False', '<button aria-expanded="False">x</button>', {'aria-valid-attr-value':'!fail'});
add('aria-current PAGE', '<a href="/" aria-current="PAGE">x</a>', {'aria-valid-attr-value':'!fail'});
add('label-in-name hyphen', '<a href="/" aria-label="Sign in to account">Sign-in</a>', {'label-in-name':'!fail'});
add('label-in-name submitting', '<button aria-label="Submitting">Submit</button>', {'label-in-name':'fail'});
add('label-in-name punct', '<a href="/" aria-label="Learn more, about pricing">Learn more</a>', {'label-in-name':'pass'});
add('label-in-name pdf', '<a href="/r.pdf" aria-label="Download (PDF, 2 MB)">Download PDF</a>', {'label-in-name':'!fail'});
add('label-in-name number', '<button aria-label="Page 2 of 5">2</button>', {'label-in-name':'!fail'});
add('label-in-name case', '<button aria-label="SEND message">send</button>', {'label-in-name':'pass'});
add('label-in-name dismiss', '<button aria-label="Dismiss">Close</button>', {'label-in-name':'fail'});
add('label-in-name nbsp', '<button aria-label="Next page">Next&nbsp;page</button>', {'label-in-name':'pass'});
add('label-in-name sr-only extra', '<style>.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}</style><a href="/" aria-label="Read more about cats">Read more<span class=sr> about cats</span></a>', {'label-in-name':'pass'});
add('label-in-name icon text', '<button aria-label="Search the site"><svg aria-hidden=true></svg> Search</button>', {'label-in-name':'pass'});
add('label-in-name labelledby', '<button aria-labelledby="l1">Buy</button><span id=l1>Buy now</span>', {'label-in-name':'pass'});
add('label-in-name title', '<button title="Delete item">Delete</button>', {'label-in-name':'!fail'});
add('label-in-name input', '<label for=fn>First name</label><input id=fn type=text aria-label="Given name">', {});
add('label-in-name em', '<button aria-label="Add to cart">Add <em>to</em> cart</button>', {'label-in-name':'pass'});
add('label-in-name multiline', '<a href="/" aria-label="Contact us today">Contact<br>us</a>', {'label-in-name':'pass'});
add('label-in-name link text with img alt', '<a href="/" aria-label="ACME homepage"><img src=l.png alt="ACME"></a>', {'label-in-name':'!fail'});
add('textarea chromium', '<label>Msg <textarea></textarea></label>', {'scrollable-region-focusable':'!fail'});
add('aria-hidden iframe', '<div aria-hidden=true><iframe src="about:blank" title="t"></iframe></div>', {});
add('aria-hidden iframe tabindex-1', '<div aria-hidden=true><iframe src="about:blank" title="t" tabindex=-1></iframe></div>', {'aria-hidden-focus':'!fail'});
add('inert link inside aria-hidden', '<div aria-hidden=true><div inert><a href="/">x</a></div></div>', {'aria-hidden-focus':'pass'});
add('aria-hidden dialog closed link', '<div aria-hidden=true><dialog><a href="/">x</a></dialog></div>', {'aria-hidden-focus':'!fail'});
add('aria-hidden video controls', '<div aria-hidden=true><video controls src=v.mp4></video></div>', {});
add('aria-hidden audio no controls', '<div aria-hidden=true><audio src=a.mp3></audio></div>', {'aria-hidden-focus':'!fail'});
add('aria-hidden area', '<div aria-hidden=true><img src=m.png usemap="#mm" alt=""><map name=mm><area href="/" alt="x" shape=rect coords="0,0,5,5"></map></div>', {});
add('aria-hidden a in svg', '<svg aria-hidden=true viewBox="0 0 1 1"><a href="/"><text>x</text></a></svg>', {'aria-hidden-focus':'fail'});
add('icon in named link', '<a href="/cart"><svg aria-hidden=true viewBox="0 0 1 1"></svg> Cart</a><a href="/acct"><svg aria-hidden=true viewBox="0 0 1 1"></svg> Account</a>', {'img-alt-decorative':'!cantTell'});
add('video poster w/ figcaption', '<figure><video controls poster=p.jpg src=v.mp4></video><figcaption>Product demo video</figcaption></figure>', {'video-poster-text-alternative-present':'!fail'});
add('video poster aria-hidden', '<video poster=p.jpg src=v.mp4 aria-hidden=true></video>', {});
add('canvas bg aria-hidden', '<canvas aria-hidden=true width=5 height=5></canvas>', {'canvas-text-alternative-present':'!fail'});
add('heading role=none text', '<h2 role=none>Not a heading</h2>', {'empty-heading':'!fail'});
add('h1 hidden', '<h2 hidden></h2>', {'empty-heading':'!fail'});
add('aria-level 7', '<div role=heading aria-level=7>Deep</div>', {'aria-valid-attr-value':'!fail'});
add('heading aria-level on h tag', '<h2 aria-level=4>X</h2>', {});
add('ul w/ li role=presentation', '<ul role=presentation><li role=presentation>a</li></ul>', {'listitem-parent-valid':'!fail','list-children-valid':'!fail'});
add('ul li custom element', '<ul><x-item>a</x-item></ul>', {});
add('ul li slot-like', '<ul><li>a</li><!-- c --></ul>', {'list-children-valid':'pass'});
add('ol li role listitem with div wrapper role none', '<ol><div role=none><li>a</li></div></ol>', {});
add('table summary role=none td', '<table role=none><tr><th>A</th></tr><tr><td>1</td></tr></table>', {'table-th-has-data-cells':'!fail'});
add('table caption only header scope=row td', '<table><tr><th scope=row>Name</th><td>Ann</td></tr><tr><th scope=row>Age</th><td>4</td></tr></table>', {'table-th-has-data-cells':'pass','td-has-header':'!fail'});
add('scope invalid', '<table><tr><th scope=column>A</th></tr><tr><td>1</td></tr></table>', {});
add('scope on td', '<table><tr><td scope=col>A</td></tr><tr><td>1</td></tr></table>', {});
add('scope rowgroup', '<table><tbody><tr><th scope=rowgroup>G</th><td>1</td></tr></tbody></table>', {'scope-attr-valid':'!cantTell'});
add('lang qaa on p', '<p lang=qaa>x</p>', {'valid-lang':'!fail'});
add('lang i-klingon on p', '<p lang=i-klingon>x</p>', {});
add('lang und', '<p lang=und>x</p>', {'valid-lang':'!fail'});
add('lang zxx', '<p lang=zxx>x</p>', {'valid-lang':'!fail'});
add('lang mul', '<p lang=mul>x</p>', {'valid-lang':'!fail'});
add('lang ar-Latn', '<p lang="ar-Latn">x</p>', {'valid-lang':'pass'});
add('lang trailing dash', '<p lang="en-">x</p>', {'valid-lang':'fail'});
add('lang 3-letter iso639-3', '<p lang="haw">x</p>', {'valid-lang':'pass'});
add('lang sr-Cyrl-RS', '<p lang="sr-Cyrl-RS">x</p>', {'valid-lang':'pass'});
add('lang ja-JP-u-ca-japanese', '<p lang="ja-JP-u-ca-japanese">x</p>', {'valid-lang':'pass'});
add('lang on aria-hidden', '<p lang="xyzzy" aria-hidden=true>x</p>', {});
add('lang on hidden text', '<p lang="xyzzy" hidden>x</p>', {'valid-lang':'!fail'});
add('autocomplete appropriate type', '<label>Phone <input type=email autocomplete="tel"></label>', {});
add('autocomplete chrome-off', '<label>Q <input type=text autocomplete="chrome-off"></label>', {});
add('autocomplete readonly', '<label>Q <input type=text readonly autocomplete="foo"></label>', {});
add('autocomplete checkbox', '<label>Q <input type=checkbox autocomplete="email"></label>', {});
add('autocomplete form-level off', '<form autocomplete=off><label>Q <input type=text></label></form>', {'autocomplete-valid':'!fail'});
add('accesskey single', '<a href="/" accesskey=h>Home</a>', {'accesskeys':'!cantTell'});
add('tabindex -1 programmatic', '<div tabindex=-1 id=main2>x</div>', {'tabindex':'!cantTell'});
add('focusable role=presentation div tabindex=0', '<div role=presentation tabindex=0>x</div>', {});
add('mouse only handler', '<div onclick="go()">Click</div>', {});
add('mouse with key', '<div onclick="go()" onkeydown="go()" role=button tabindex=0>Click</div>', {'mouse-only-event-handlers':'!cantTell'});
add('password input', '<label>Password <input type=password></label>', {'password-paste-enabled':'!cantTell'});
add('p as heading', '<p><b>Section title</b></p><p>Body text that follows here.</p>', {});
add('details nested interactive in summary', '<details><summary>Filter <input type=checkbox aria-label=all></summary>x</details>', {});
add('dialog modal name via h2', '<dialog open aria-labelledby=dh2><h2 id=dh2>Settings</h2></dialog>', {'dialog-name-present':'pass'});
add('generic named by aria-label w/ role group', '<div role=group aria-label="Shipping">x</div>', {'aria-prohibited-attr':'!fail'});
add('multiple role tokens nav', '<div role="foo navigation"><a href="/">x</a></div><div role="foo navigation"><a href="/">y</a></div>', {});
module.exports=C;
