'use strict';

/**
 * Generate profiles/acme/part-a.js: ACME Part A restates every WCAG
 * A and AA criterion of the WCAG version each ACME version is built on, as
 * requirement `A.<sc>`.
 *
 * The table is generated rather than computed at run time because a
 * profile's own files may not require core's modules (profiles/README.md),
 * while its scripts may read WCAG's reference tables. See finding F1 in
 * DESIGN.md.
 *
 * Usage:
 *   node profiles/acme/scripts/generate-part-a.js           write the module
 *   node profiles/acme/scripts/generate-part-a.js --check   exit 1 if it is out of date
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..', '..', '..');
const OUTPUT_FILE = path.join(__dirname, '..', 'part-a.js');

const { FACETS } = require('../../../src/coverage/wcag-facets');
const { introducedInVersion, removedInVersion } = require('../../../src/coverage/wcag-version-map');

const VERSIONS = [
  { version: '1.0', wcagVersion: '2.1' },
  { version: '2.0', wcagVersion: '2.2' }
];
const WCAG_ORDER = ['2.0', '2.1', '2.2'];

function compareSc(a, b) {
  const pa = a.split('.').map(Number);
  const pb = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) if (pa[i] !== pb[i]) return pa[i] - pb[i];
  return 0;
}

// The A and AA criteria in force in one WCAG version. Core's table describes
// WCAG 2.2, where 4.1.1 has no level and is titled "Parsing (Obsolete and
// removed)"; in 2.1 it was a Level A criterion titled "Parsing". So a removed
// criterion is taken as in force before its removal, whatever its level
// says (finding F2 in DESIGN.md).
function criteriaOf(wcagVersion) {
  const max = WCAG_ORDER.indexOf(wcagVersion);
  return Object.keys(FACETS)
    .filter((sc) => FACETS[sc].level !== 'AAA')
    .filter((sc) => WCAG_ORDER.indexOf(introducedInVersion(sc)) <= max)
    .filter((sc) => {
      const removed = removedInVersion(sc);
      return !(removed && WCAG_ORDER.indexOf(removed) <= max);
    })
    .sort(compareSc);
}

function buildTable() {
  const table = {};
  for (const { version, wcagVersion } of VERSIONS) {
    table[version] = {};
    for (const sc of criteriaOf(wcagVersion)) {
      const title = FACETS[sc].title.replace(/\s*\(Obsolete and removed\)$/, '');
      table[version][sc] = { requirement: `A.${sc}`, title };
    }
  }
  return table;
}

function renderModule(table) {
  return `/* SPDX-License-Identifier: MPL-2.0 */

'use strict';

/**
 * ACME Part A: the WCAG A and AA criteria each ACME version restates, as
 * requirement \`A.<sc>\`. ACME is a made-up standard that tests the profile
 * model (DESIGN.md); it never ships.
 *
 * GENERATED by profiles/acme/scripts/generate-part-a.js -- do not
 * edit by hand.
 */

const ACME_VERSIONS = ${JSON.stringify(VERSIONS)};

const ACME_PART_A = ${JSON.stringify(table)};

module.exports = { ACME_VERSIONS, ACME_PART_A };
`;
}

async function formatted(source) {
  const prettier = require('prettier');
  const options = (await prettier.resolveConfig(OUTPUT_FILE)) || {};
  return prettier.format(source, { ...options, filepath: OUTPUT_FILE });
}

async function main() {
  const expected = await formatted(renderModule(buildTable()));
  const rel = path.relative(ROOT_DIR, OUTPUT_FILE);
  if (process.argv.includes('--check')) {
    const actual = fs.existsSync(OUTPUT_FILE) ? fs.readFileSync(OUTPUT_FILE, 'utf8') : '';
    if (actual !== expected) {
      console.error(
        `[acme-part-a] ${rel} is out of date; run node profiles/acme/scripts/generate-part-a.js`
      );
      process.exit(1);
    }
    console.log('[acme-part-a] up to date');
    return;
  }
  fs.writeFileSync(OUTPUT_FILE, expected, 'utf8');
  console.log(`[acme-part-a] wrote ${rel}`);
}

module.exports = { buildTable, renderModule, formatted, criteriaOf };

if (require.main === module) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
