/* SPDX-License-Identifier: MPL-2.0 */

'use strict';

/**
 * ACME Part A: the WCAG A and AA criteria each ACME version restates, as
 * requirement `A.<sc>`. ACME is a made-up standard that tests the profile
 * model (DESIGN.md); it never ships.
 *
 * GENERATED by profiles/acme/scripts/generate-part-a.js -- do not
 * edit by hand.
 */

const ACME_VERSIONS = [
  { version: '1.0', wcagVersion: '2.1' },
  { version: '2.0', wcagVersion: '2.2' }
];

const ACME_PART_A = {
  '1.0': {
    '1.1.1': { requirement: 'A.1.1.1', title: 'Non-text Content' },
    '1.2.1': { requirement: 'A.1.2.1', title: 'Audio-only and Video-only (Prerecorded)' },
    '1.2.2': { requirement: 'A.1.2.2', title: 'Captions (Prerecorded)' },
    '1.2.3': {
      requirement: 'A.1.2.3',
      title: 'Audio Description or Media Alternative (Prerecorded)'
    },
    '1.2.4': { requirement: 'A.1.2.4', title: 'Captions (Live)' },
    '1.2.5': { requirement: 'A.1.2.5', title: 'Audio Description (Prerecorded)' },
    '1.3.1': { requirement: 'A.1.3.1', title: 'Info and Relationships' },
    '1.3.2': { requirement: 'A.1.3.2', title: 'Meaningful Sequence' },
    '1.3.3': { requirement: 'A.1.3.3', title: 'Sensory Characteristics' },
    '1.3.4': { requirement: 'A.1.3.4', title: 'Orientation' },
    '1.3.5': { requirement: 'A.1.3.5', title: 'Identify Input Purpose' },
    '1.4.1': { requirement: 'A.1.4.1', title: 'Use of Color' },
    '1.4.2': { requirement: 'A.1.4.2', title: 'Audio Control' },
    '1.4.3': { requirement: 'A.1.4.3', title: 'Contrast (Minimum)' },
    '1.4.4': { requirement: 'A.1.4.4', title: 'Resize Text' },
    '1.4.5': { requirement: 'A.1.4.5', title: 'Images of Text' },
    '1.4.10': { requirement: 'A.1.4.10', title: 'Reflow' },
    '1.4.11': { requirement: 'A.1.4.11', title: 'Non-text Contrast' },
    '1.4.12': { requirement: 'A.1.4.12', title: 'Text Spacing' },
    '1.4.13': { requirement: 'A.1.4.13', title: 'Content on Hover or Focus' },
    '2.1.1': { requirement: 'A.2.1.1', title: 'Keyboard' },
    '2.1.2': { requirement: 'A.2.1.2', title: 'No Keyboard Trap' },
    '2.1.4': { requirement: 'A.2.1.4', title: 'Character Key Shortcuts' },
    '2.2.1': { requirement: 'A.2.2.1', title: 'Timing Adjustable' },
    '2.2.2': { requirement: 'A.2.2.2', title: 'Pause, Stop, Hide' },
    '2.3.1': { requirement: 'A.2.3.1', title: 'Three Flashes or Below Threshold' },
    '2.4.1': { requirement: 'A.2.4.1', title: 'Bypass Blocks' },
    '2.4.2': { requirement: 'A.2.4.2', title: 'Page Titled' },
    '2.4.3': { requirement: 'A.2.4.3', title: 'Focus Order' },
    '2.4.4': { requirement: 'A.2.4.4', title: 'Link Purpose (In Context)' },
    '2.4.5': { requirement: 'A.2.4.5', title: 'Multiple Ways' },
    '2.4.6': { requirement: 'A.2.4.6', title: 'Headings and Labels' },
    '2.4.7': { requirement: 'A.2.4.7', title: 'Focus Visible' },
    '2.5.1': { requirement: 'A.2.5.1', title: 'Pointer Gestures' },
    '2.5.2': { requirement: 'A.2.5.2', title: 'Pointer Cancellation' },
    '2.5.3': { requirement: 'A.2.5.3', title: 'Label in Name' },
    '2.5.4': { requirement: 'A.2.5.4', title: 'Motion Actuation' },
    '3.1.1': { requirement: 'A.3.1.1', title: 'Language of Page' },
    '3.1.2': { requirement: 'A.3.1.2', title: 'Language of Parts' },
    '3.2.1': { requirement: 'A.3.2.1', title: 'On Focus' },
    '3.2.2': { requirement: 'A.3.2.2', title: 'On Input' },
    '3.2.3': { requirement: 'A.3.2.3', title: 'Consistent Navigation' },
    '3.2.4': { requirement: 'A.3.2.4', title: 'Consistent Identification' },
    '3.3.1': { requirement: 'A.3.3.1', title: 'Error Identification' },
    '3.3.2': { requirement: 'A.3.3.2', title: 'Labels or Instructions' },
    '3.3.3': { requirement: 'A.3.3.3', title: 'Error Suggestion' },
    '3.3.4': { requirement: 'A.3.3.4', title: 'Error Prevention (Legal, Financial, Data)' },
    '4.1.1': { requirement: 'A.4.1.1', title: 'Parsing' },
    '4.1.2': { requirement: 'A.4.1.2', title: 'Name, Role, Value' },
    '4.1.3': { requirement: 'A.4.1.3', title: 'Status Messages' }
  },
  '2.0': {
    '1.1.1': { requirement: 'A.1.1.1', title: 'Non-text Content' },
    '1.2.1': { requirement: 'A.1.2.1', title: 'Audio-only and Video-only (Prerecorded)' },
    '1.2.2': { requirement: 'A.1.2.2', title: 'Captions (Prerecorded)' },
    '1.2.3': {
      requirement: 'A.1.2.3',
      title: 'Audio Description or Media Alternative (Prerecorded)'
    },
    '1.2.4': { requirement: 'A.1.2.4', title: 'Captions (Live)' },
    '1.2.5': { requirement: 'A.1.2.5', title: 'Audio Description (Prerecorded)' },
    '1.3.1': { requirement: 'A.1.3.1', title: 'Info and Relationships' },
    '1.3.2': { requirement: 'A.1.3.2', title: 'Meaningful Sequence' },
    '1.3.3': { requirement: 'A.1.3.3', title: 'Sensory Characteristics' },
    '1.3.4': { requirement: 'A.1.3.4', title: 'Orientation' },
    '1.3.5': { requirement: 'A.1.3.5', title: 'Identify Input Purpose' },
    '1.4.1': { requirement: 'A.1.4.1', title: 'Use of Color' },
    '1.4.2': { requirement: 'A.1.4.2', title: 'Audio Control' },
    '1.4.3': { requirement: 'A.1.4.3', title: 'Contrast (Minimum)' },
    '1.4.4': { requirement: 'A.1.4.4', title: 'Resize Text' },
    '1.4.5': { requirement: 'A.1.4.5', title: 'Images of Text' },
    '1.4.10': { requirement: 'A.1.4.10', title: 'Reflow' },
    '1.4.11': { requirement: 'A.1.4.11', title: 'Non-text Contrast' },
    '1.4.12': { requirement: 'A.1.4.12', title: 'Text Spacing' },
    '1.4.13': { requirement: 'A.1.4.13', title: 'Content on Hover or Focus' },
    '2.1.1': { requirement: 'A.2.1.1', title: 'Keyboard' },
    '2.1.2': { requirement: 'A.2.1.2', title: 'No Keyboard Trap' },
    '2.1.4': { requirement: 'A.2.1.4', title: 'Character Key Shortcuts' },
    '2.2.1': { requirement: 'A.2.2.1', title: 'Timing Adjustable' },
    '2.2.2': { requirement: 'A.2.2.2', title: 'Pause, Stop, Hide' },
    '2.3.1': { requirement: 'A.2.3.1', title: 'Three Flashes or Below Threshold' },
    '2.4.1': { requirement: 'A.2.4.1', title: 'Bypass Blocks' },
    '2.4.2': { requirement: 'A.2.4.2', title: 'Page Titled' },
    '2.4.3': { requirement: 'A.2.4.3', title: 'Focus Order' },
    '2.4.4': { requirement: 'A.2.4.4', title: 'Link Purpose (In Context)' },
    '2.4.5': { requirement: 'A.2.4.5', title: 'Multiple Ways' },
    '2.4.6': { requirement: 'A.2.4.6', title: 'Headings and Labels' },
    '2.4.7': { requirement: 'A.2.4.7', title: 'Focus Visible' },
    '2.4.11': { requirement: 'A.2.4.11', title: 'Focus Not Obscured (Minimum)' },
    '2.5.1': { requirement: 'A.2.5.1', title: 'Pointer Gestures' },
    '2.5.2': { requirement: 'A.2.5.2', title: 'Pointer Cancellation' },
    '2.5.3': { requirement: 'A.2.5.3', title: 'Label in Name' },
    '2.5.4': { requirement: 'A.2.5.4', title: 'Motion Actuation' },
    '2.5.7': { requirement: 'A.2.5.7', title: 'Dragging Movements' },
    '2.5.8': { requirement: 'A.2.5.8', title: 'Target Size (Minimum)' },
    '3.1.1': { requirement: 'A.3.1.1', title: 'Language of Page' },
    '3.1.2': { requirement: 'A.3.1.2', title: 'Language of Parts' },
    '3.2.1': { requirement: 'A.3.2.1', title: 'On Focus' },
    '3.2.2': { requirement: 'A.3.2.2', title: 'On Input' },
    '3.2.3': { requirement: 'A.3.2.3', title: 'Consistent Navigation' },
    '3.2.4': { requirement: 'A.3.2.4', title: 'Consistent Identification' },
    '3.2.6': { requirement: 'A.3.2.6', title: 'Consistent Help' },
    '3.3.1': { requirement: 'A.3.3.1', title: 'Error Identification' },
    '3.3.2': { requirement: 'A.3.3.2', title: 'Labels or Instructions' },
    '3.3.3': { requirement: 'A.3.3.3', title: 'Error Suggestion' },
    '3.3.4': { requirement: 'A.3.3.4', title: 'Error Prevention (Legal, Financial, Data)' },
    '3.3.7': { requirement: 'A.3.3.7', title: 'Redundant Entry' },
    '3.3.8': { requirement: 'A.3.3.8', title: 'Accessible Authentication (Minimum)' },
    '4.1.2': { requirement: 'A.4.1.2', title: 'Name, Role, Value' },
    '4.1.3': { requirement: 'A.4.1.3', title: 'Status Messages' }
  }
};

module.exports = { ACME_VERSIONS, ACME_PART_A };
