'use strict';

/**
 * Generate profiles/rgaa/map.js from the RGAA source data in
 * profiles/rgaa/data/ (see the README there for provenance and licence).
 *
 * Usage:
 *   node profiles/rgaa/scripts/generate-map.js           write the module
 *   node profiles/rgaa/scripts/generate-map.js --check   exit 1 if it is out of date
 *
 * The text is RGAA's own, in French, with only its Markdown taken out:
 * glossary links keep their words and code spans lose their backticks, so
 * "Chaque [image porteuse d’information](#image-porteuse-d-information)"
 * becomes "Chaque image porteuse d’information". Nothing is translated or
 * reworded.
 */

const fs = require('fs');
const path = require('path');

const PROFILE_DIR = path.join(__dirname, '..');
const DATA_DIR = path.join(PROFILE_DIR, 'data');
const OUTPUT_FILE = path.join(PROFILE_DIR, 'map.js');

// Oldest first. `published` is when the version appeared in the source
// repository; `wcagVersion` is the WCAG version its criteria are built on.
const SOURCES = [
  { version: '4.1.2', published: '2023-04', wcagVersion: '2.1', file: 'criteres-4.1.2.json' }
];

function plainText(markdown) {
  return String(markdown)
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/`([^`]*)`/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();
}

// "1.1.1 Non-text Content (A)" -> "1.1.1"
function wcagScOf(reference) {
  const m = /^(\d+\.\d+\.\d+) .+ \((A|AA|AAA)\)$/.exec(String(reference).trim());
  if (!m) throw new Error(`[generate-rgaa-map] unrecognised WCAG reference: ${reference}`);
  return m[1];
}

function referencesOf(criterium, kind) {
  return (criterium.references || []).flatMap((r) => (Array.isArray(r[kind]) ? r[kind] : []));
}

/**
 * The tables for one version of the source file: themes, criteria keyed
 * "1.1", tests keyed "1.1.1".
 */
function buildVersionTables(source) {
  const themes = [];
  const criteria = {};
  const tests = {};
  for (const topic of source.topics) {
    themes.push({ number: topic.number, title: plainText(topic.topic) });
    for (const { criterium } of topic.criteria) {
      const id = `${topic.number}.${criterium.number}`;
      const testIds = Object.keys(criterium.tests)
        .sort((a, b) => Number(a) - Number(b))
        .map((n) => `${id}.${n}`);
      criteria[id] = {
        theme: topic.number,
        title: plainText(criterium.title),
        wcagSc: [...new Set(referencesOf(criterium, 'wcag').map(wcagScOf))],
        techniques: referencesOf(criterium, 'techniques').map(String),
        tests: testIds
      };
      for (const testId of testIds) {
        const [question, ...conditions] = criterium.tests[testId.slice(id.length + 1)];
        tests[testId] = {
          criterion: id,
          title: plainText(question),
          ...(conditions.length ? { conditions: conditions.map(plainText) } : {})
        };
      }
    }
  }
  return { themes, criteria, tests };
}

function buildTables(readSource = (file) => fs.readFileSync(path.join(DATA_DIR, file), 'utf8')) {
  const out = { versions: [], themes: {}, criteria: {}, tests: {} };
  for (const { version, published, wcagVersion, file } of SOURCES) {
    const t = buildVersionTables(JSON.parse(readSource(file)));
    out.versions.push({ version, published, wcagVersion });
    out.themes[version] = t.themes;
    out.criteria[version] = t.criteria;
    out.tests[version] = t.tests;
  }
  return out;
}

function renderModule(tables) {
  const json = (v) => JSON.stringify(v, null, 2);
  return `/* SPDX-License-Identifier: MPL-2.0 */

'use strict';

/**
 * RGAA (Référentiel général d’amélioration de l’accessibilité), the French
 * accessibility standard: its themes, criteria and tests, per version.
 *
 * GENERATED by profiles/rgaa/scripts/generate-map.js from profiles/rgaa/data/
 * -- do not edit by hand; profiles/rgaa/tests/map.test.js fails on any drift.
 *
 * SOURCE: RGAA 4.1.2, DINUM, https://github.com/DISIC/accessibilite.numerique.gouv.fr
 * (RGAA/criteres.json), published under Licence Ouverte 2.0. The text is
 * RGAA's own French wording with its Markdown removed.
 *
 * SHAPE
 * -----
 * - RGAA_VERSIONS: [{ version, published, wcagVersion }], oldest first.
 * - RGAA_THEMES[version]: [{ number, title }], the 13 themes in order.
 * - RGAA_CRITERIA[version]["1.1"]: { theme, title, wcagSc, techniques, tests }.
 *   \`wcagSc\` is RGAA's own correspondence to WCAG; \`techniques\` the WCAG
 *   techniques and failures it cites; \`tests\` the ids of its tests.
 * - RGAA_TESTS[version]["1.1.1"]: { criterion, title, conditions? }.
 *   \`conditions\` lists what a test enumerates ("vérifie-t-il une de ces
 *   conditions ?").
 *
 * Like the EN 301 549 table, this states what a published document says,
 * nothing more: which version applies to whom is not an engine question.
 */

const RGAA_VERSIONS = ${json(tables.versions)};

const RGAA_THEMES = ${json(tables.themes)};

const RGAA_CRITERIA = ${json(tables.criteria)};

const RGAA_TESTS = ${json(tables.tests)};

// The criteria of every version that RGAA itself relates to a WCAG Success
// Criterion, oldest version first: [{ version, criterion, title }].
function rgaaCriteriaForSc(sc) {
  const s = String(sc || '').trim();
  const out = [];
  for (const { version } of RGAA_VERSIONS) {
    for (const [criterion, row] of Object.entries(RGAA_CRITERIA[version])) {
      if (row.wcagSc.includes(s)) out.push({ version, criterion, title: row.title });
    }
  }
  return out;
}

module.exports = { RGAA_VERSIONS, RGAA_THEMES, RGAA_CRITERIA, RGAA_TESTS, rgaaCriteriaForSc };
`;
}

async function formatted(source) {
  const prettier = require('prettier');
  const options = (await prettier.resolveConfig(OUTPUT_FILE)) || {};
  return prettier.format(source, { ...options, filepath: OUTPUT_FILE });
}

async function main() {
  const expected = await formatted(renderModule(buildTables()));
  if (process.argv.includes('--check')) {
    const actual = fs.existsSync(OUTPUT_FILE) ? fs.readFileSync(OUTPUT_FILE, 'utf8') : '';
    if (actual !== expected) {
      console.error(
        `[generate-rgaa-map] ${path.relative(process.cwd(), OUTPUT_FILE)} is out of date; run npm run rgaa-map`
      );
      process.exit(1);
    }
    console.log('[generate-rgaa-map] up to date');
    return;
  }
  fs.writeFileSync(OUTPUT_FILE, expected, 'utf8');
  console.log(`[generate-rgaa-map] wrote ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

module.exports = { SOURCES, plainText, buildTables, renderModule, formatted };

if (require.main === module) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
