const p=require('./h');
const L=['label-in-name'];
p('split word inline','<a href="/d" aria-label="Download the report"><b>Down</b>load</a>',L);
p('split first letter','<button aria-label="Submit form"><span class="cap">S</span>ubmit</button>',L);
p('select in label','<label>Quantity <select aria-label="Quantity"><option>1</option><option>2</option></select></label>',L);
p('textarea in label','<label>Comments <textarea aria-label="Comments">Hello</textarea></label>',L);
p('sr-only text','<style>.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}</style><button aria-label="Close dialog"><span class="sr">Dismiss</span>Close</button>',L);
p('visibility hidden child','<button aria-label="Close"><span style="visibility:hidden">Dismiss</span>Close</button>',L);
p('opacity 0 child','<button aria-label="Close"><span style="opacity:0">Dismiss</span>Close</button>',L);
p('label with nested button-ish', '<label for="e">Email <span class="req" title="required">*</span></label><input id="e" aria-label="Email">',L);
p('a href with tooltip span hidden by CSS display none class','<style>.tip{display:none}</style><a href="/" aria-label="Home"><span>Home</span><span class="tip">Go to homepage</span></a>',L);
p('checkbox label with link','<input type="checkbox" id="c" aria-label="Accept terms"><label for="c">Accept <a href="/t">terms</a></label>',L);
p('input type=submit value','<input type="submit" value="Search" aria-label="Search site">',L);
p('input type=submit value mismatch','<input type="submit" value="Go" aria-label="Search site">',L);
p('input type=button value only','<input type="button" value="Go now" aria-label="Go">',L);
p('img alt inside link','<a href="/" aria-label="Home"><img src="logo.png" alt="Acme"></a>',L);
p('label hidden via aria-hidden not excluded?', '<label for="i">Name</label><input id="i" aria-label="Full name">',L);
p('nbsp/emdash', '<button aria-label="Next — page">Next&nbsp;page</button>',L);
p('soft hyphen', '<button aria-label="Download">Down&shy;load</button>',L);
p('zero width joiner', '<button aria-label="Download">Down&#8203;load</button>',L);
p('apostrophe', '<button aria-label="Dont save">Don’t save</button>',L);
p('display none inside label','<label for="q">Search<span style="display:none">secret</span></label><input id="q" aria-label="Search">',L);
