const n=require('./n');
n('<button id="b"><b>Down</b>load</button>','b');
n('<button id="b">Save<div>file</div></button>','b');
n('<a id="b" href="#">Save<br>file</a>','b');
n('<a id="b" href="#"><span>Save</span><span>file</span></a>','b');
n('<a id="b" href="#"><img alt="Save" src=x><img alt="file" src=x></a>','b');
n('<button id="b">Down&shy;load</button>','b');
n('<button id="b"><span aria-label="Close">X</span></button>','b');
n('<button id="b"><span title="Close"></span></button>','b');
n('<button id="b"><span role="img" title="Close"></span></button>','b');
n('<button id="b"><select><option>A</option><option selected>B</option></select></button>','b');
n('<button id="b">Volume <input type="range" min=0 max=10 value=4></button>','b');
n('<button id="b">Qty <input type="number" value=4></button>','b');
n('<button id="b">Qty <span role="spinbutton" aria-valuenow="4" aria-valuetext="four"></span></button>','b');
n('<button id="b">Save <span hidden>secret</span></button>','b');
n('<button id="b">Save <span aria-hidden="true">X</span></button>','b');
n('<button id="b"><svg><title>Save</title></svg></button>','b');
n('<button id="b"><svg aria-hidden="true"><title>Save</title></svg></button>','b');
n('<button id="b"><svg role="presentation"><title>Save</title></svg></button>','b');
n('<button id="b"><abbr title="Save">S</abbr></button>','b');
n('<button id="b"><input type="checkbox" aria-label="x">Save</button>','b');
n('<a id="b" href="#"><div role="heading" aria-level="2">Title</div></a>','b');
n('<a id="b" href="#"><ul><li>One</li></ul></a>','b');
n('<a id="b" href="#">One<template>Two</template></a>','b');
n('<a id="b" href="#">One<noscript>Two</noscript></a>','b');
n('<a id="b" href="#">One<style>.x{}</style></a>','b');
n('<a id="b" href="#"><span style="display:contents">One</span></a>','b');
n('<a id="b" href="#"><table><tr><td>A</td><td>B</td></tr></table></a>','b');
