const n=require('./n');
const F='getAccessibleNameInfo';
n('<button id="b" aria-labelledby="a"></button><span id="a" aria-label="Save"></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a"><img alt="Save" src=x></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a" title="Save"></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><input id="a" value="Save">','b',F);
n('<button id="b" aria-labelledby="a"></button><select id="a"><option>One</option><option selected>Save</option></select>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a" hidden>Save <span>file</span></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Save<span hidden>X</span></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Save<span aria-hidden="true">X</span></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><div id="a" aria-hidden="true">Save<span>X</span></div>','b',F);
n('<button id="b" aria-labelledby="a b"></button><span id="a">Save</span><span id="b2">x</span>','b',F);
n('<button id="b" aria-labelledby="a a"></button><span id="a">Save</span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a"><b>Sa</b>ve</span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Save <button aria-label="Inner">I</button></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Rate <input type="range" min="0" max="10" value="7" aria-valuetext="seven"></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Rate <span role="slider" aria-valuenow="7"></span></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Rate <span role="textbox">abc</span></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Pick <span role="combobox" aria-activedescendant=""><span>Red</span></span></span>','b',F);
n('<button id="b" aria-labelledby="a"></button><span id="a">Pick <span role="listbox"><span role="option" aria-selected="true">Red</span><span role="option">Blue</span></span></span>','b',F);
n('<input id="b" aria-labelledby="a"><label id="a">Name <input value="x" id="other"></label>','b',F);
n('<input id="b"><label for="b">Name <input value="ignored" id="other"></label>','b',F);
n('<input id="b" type="checkbox"><label for="b">Remind me in <select><option selected>3</option></select> days</label>','b',F);
n('<input id="b" type="checkbox"><label for="b">Remind me in <input type="number" value="3"> days</label>','b',F);
n('<input id="b"><label for="b" aria-label="Override">Visible</label>','b',F);
n('<input id="b"><label for="b"><span aria-label="Override">Visible</span></label>','b',F);
n('<input id="b" title="T" placeholder="P">','b',F);
n('<input id="b" placeholder="P">','b',F);
n('<input id="b" aria-placeholder="P">','b',F);
n('<input id="b" type="submit">','b',F);
n('<input id="b" type="button" value="Go" title="T">','b',F);
n('<textarea id="b" placeholder="Comment"></textarea>','b',F);
n('<fieldset id="b"><legend>Shipping</legend></fieldset>','b',F);
n('<table id="b"><caption>Cap</caption><tr><td>x</td></tr></table>','b',F);
n('<figure id="b"><img src=x alt=""><figcaption>Cap</figcaption></figure>','b',F);
n('<output id="b" for="x"></output><label for="b">Total</label>','b',F);
n('<meter id="b" value="0.5"></meter><label for="b">Disk</label>','b',F);
n('<progress id="b" value="0.5"></progress><label for="b">Load</label>','b',F);
