const p=require('./h');
const S=['form-control-single-label','form-control-programmatic-label-present'];
p('wrap with for=other','<label for="o">Wrap <input id="x"></label><label for="x">Real</label><input id="o">',S);
p('wrap with for=nonexistent','<label for="nope">Wrap <input id="x"></label>',S);
p('wrap with for=empty','<label for="">Wrap <input id="x"></label>',S);
p('wrap with for=self','<label for="x">Wrap <input id="x"></label>',S);
p('nested labels','<label>Outer <label>Inner <input id="x"></label></label>',S);
p('two inputs in one label','<label>Name <input id="a"> <input id="b"></label>',S);
p('label for button-type input','<label for="x">A</label><label for="x">B</label><input type="button" id="x" value="v">',S);
p('label for case','<label for="X">A</label><input id="x">',S);
p('label for with spaces','<label for=" x">A</label><input id="x">',S);
p('label wrapped in for= duplicate id','<label for="x">A</label><input id="x"><input id="x">',S);
p('input type=checkbox label + aria-labelledby on label', '<input type="checkbox" id="c"><label for="c">Agree</label><label for="c">Terms</label>',S);
p('two labels one hidden by visibility', '<input id="c"><label for="c">Agree</label><label for="c" style="visibility:hidden">Terms</label>',S);
p('input in label with aria-hidden label', '<label aria-hidden="true">Name <input id="x"></label>',S);
p('label aria-hidden display', '<label for="x" aria-hidden="true">Name</label><input id="x">',S);
p('input type=file','<input type="file">',S);
p('input type=color','<input type="color">',S);
p('input type=range','<input type="range">',S);
p('input type=checkbox in fieldset legend only','<fieldset><legend>Agree</legend><input type="checkbox"></fieldset>',S);
p('select with aria-label empty and title','<select aria-label=" " title="Size"><option>1</option></select>',S);
p('input type=image no alt','<input type="image" src="x">',S);
p('textarea placeholder only','<textarea placeholder="Comment"></textarea>',S);
p('input type=search role=searchbox','<input type="search" role="searchbox">',S);
p('input type=text role=combobox','<input role="combobox">',S);
p('input list (combobox implicit)','<input list="l"><datalist id="l"><option value="a"></datalist>',S);
p('input type=email list','<input type="email" list="l"><datalist id="l"><option value="a"></datalist>',S);
p('input in label pointing elsewhere via for on another label','<label>Wrap <input id="x"></label><label for="x">  </label>',S);
