const p=require('./h');
const B=['button-name-present'];
p('role fallback list','<div role="foo button" tabindex="0"></div>',B);
p('uppercase role','<div role="BUTTON" tabindex="0"></div>',B);
p('button with aria-labelledby to hidden elem','<button aria-labelledby="h"></button><span id="h" hidden>Save</span>',B);
p('button labelledby to display none','<button aria-labelledby="h"></button><span id="h" style="display:none">Save</span>',B);
p('button labelledby whitespace idrefs','<button aria-labelledby="  h   "></button><span id="h">Save</span>',B);
p('button labelledby missing + aria-label','<button aria-labelledby="nope" aria-label="Save"></button>',B);
p('button labelledby to empty + content','<button aria-labelledby="e">Save</button><span id="e"></span>',B);
p('button with title only','<button title="Save"></button>',B);
p('button with ::before content','<style>.x::before{content:"Save"}</style><button class="x"></button>',B);
p('button with ::after alt content','<style>.x::after{content:"\\2716" / "Close"}</style><button class="x"></button>',B);
p('button with img alt','<button><img src="a.png" alt="Save"></button>',B);
p('button with svg title','<button><svg><title>Save</title></svg></button>',B);
p('button with svg aria-label','<button><svg aria-label="Save"></svg></button>',B);
p('button with svg role img aria-label','<button><svg role="img" aria-label="Save"></svg></button>',B);
p('button with aria-hidden span','<button><span aria-hidden="true">X</span></button>',B);
p('button with aria-hidden=TRUE span','<button><span aria-hidden="TRUE">X</span></button>',B);
p('input type=button value','<input type="button" value="Save">',B);
p('input type=submit no value','<input type="submit">',B);
p('input type=reset no value','<input type="reset">',B);
p('input type=button no value','<input type="button">',B);
p('input type=button value spaces','<input type="button" value="  ">',B);
p('input type=image alt','<input type="image" src="x" alt="Go">',B);
p('button role none focusable','<button role="none"></button>',B);
p('button in label','<label>Save <button></button></label>',B);
p('button with aria-label whitespace NBSP','<button aria-label="&nbsp;"></button>',B);
p('button with zero-width','<button>&#8203;</button>',B);
p('button with name from content of nested hidden visibility','<button><span style="visibility:hidden">Save</span></button>',B);
p('button with name from content of nested hidden then visible','<button style="visibility:hidden"><span style="visibility:visible">Save</span></button>',B);
p('summary', '<details><summary></summary>x</details>',['summary-name-present']);
p('button with child role=presentation img alt','<button><img role="presentation" alt="Save" src="x"></button>',B);
p('button with aria-label via slot', '<my-el></my-el><script></script>',B);
p('button with content in select', '<button><select><option>Save</option></select></button>',B);
p('button with input textbox inside', '<button><input value="Save"></button>',B);
p('div role button with text-only child role=none', '<div role="button" tabindex="0"><span role="none">Save</span></div>',B);
p('button with aria-labelledby to self', '<button id="b" aria-labelledby="b">Save</button>',B);
p('button with aria-labelledby to text in aria-hidden', '<button aria-labelledby="t"></button><div aria-hidden="true"><span id="t">Save</span></div>',B);
p('button with aria-describedby only', '<button aria-describedby="t"></button><span id="t">Save</span>',B);
