const p=require('./h');
const H=['aria-hidden-focus'];
p('aria-hidden w/ disabled button','<div aria-hidden="true"><button disabled>x</button></div>',H);
p('aria-hidden w/ fieldset disabled','<div aria-hidden="true"><fieldset disabled><input></fieldset></div>',H);
p('aria-hidden w/ fieldset disabled legend input','<div aria-hidden="true"><fieldset disabled><legend><input></legend></fieldset></div>',H);
p('aria-hidden w/ inert','<div aria-hidden="true" inert><button>x</button></div>',H);
p('aria-hidden w/ display none child','<div aria-hidden="true"><button style="display:none">x</button></div>',H);
p('aria-hidden w/ visibility hidden child','<div aria-hidden="true"><button style="visibility:hidden">x</button></div>',H);
p('aria-hidden w/ tabindex -1','<div aria-hidden="true"><button tabindex="-1">x</button></div>',H);
p('aria-hidden w/ a no href','<div aria-hidden="true"><a>x</a></div>',H);
p('aria-hidden w/ summary in closed details','<div aria-hidden="true"><details><summary>s</summary></details></div>',H);
p('aria-hidden w/ details content','<div aria-hidden="true"><details><summary tabindex="-1">s</summary><a href="#">x</a></details></div>',H);
p('aria-hidden=false inside','<div aria-hidden="true"><div aria-hidden="false"><button>x</button></div></div>',H);
p('aria-hidden=TRUE','<div aria-hidden="TRUE"><button>x</button></div>',H);
p('aria-hidden=" true "','<div aria-hidden=" true "><button>x</button></div>',H);
p('aria-hidden on focusable itself','<button aria-hidden="true">x</button>',H);
p('contenteditable','<div aria-hidden="true"><div contenteditable="true">x</div></div>',H);
p('contenteditable false','<div aria-hidden="true"><div contenteditable="false" >x</div></div>',H);
p('iframe','<div aria-hidden="true"><iframe src="about:blank" title="x"></iframe></div>',H);
p('iframe tabindex -1','<div aria-hidden="true"><iframe tabindex="-1" src="about:blank" title="x"></iframe></div>',H);
p('video controls','<div aria-hidden="true"><video controls></video></div>',H);
p('audio no controls','<div aria-hidden="true"><audio></audio></div>',H);
p('area in map','<div aria-hidden="true"><map name="m"><area href="#" alt="x" shape="rect" coords="0,0,1,1"></map></div><img usemap="#m" src="x" alt="">',H);
p('scrollable div','<div aria-hidden="true"><div style="overflow:auto;height:10px"><p>lots</p></div></div>',H);
p('select disabled','<div aria-hidden="true"><select disabled></select></div>',H);
p('input type hidden','<div aria-hidden="true"><input type="hidden"></div>',H);
p('tabindex=" -1"','<div aria-hidden="true"><button tabindex=" -1">x</button></div>',H);
p('tabindex="-1x"','<div aria-hidden="true"><button tabindex="-1x">x</button></div>',H);
p('tabindex="-0"','<div aria-hidden="true"><div tabindex="-0">x</div></div>',H);
p('a href with tabindex=-1 inside aria-hidden w/ focusable child', '<div aria-hidden="true"><a href="#" tabindex="-1"><span tabindex="0">x</span></a></div>',H);
p('svg a href', '<div aria-hidden="true"><svg><a href="#"><text>x</text></a></svg></div>',H);
p('svg a xlink:href', '<div aria-hidden="true"><svg><a xlink:href="#"><text>x</text></a></svg></div>',H);
p('button form=disabled? hidden attr until-found', '<div aria-hidden="true"><div hidden="until-found"><button>x</button></div></div>',H);
