const p=require('./h');
const N=['nested-interactive-controls-absent','presentational-children-focusable-absent'];
p('button > a','<button><a href="#">x</a></button>',N);
p('role=button > a','<div role="button" tabindex="0"><a href="#">x</a></div>',N);
p('a > button','<a href="#"><button>x</button></a>',N);
p('a > input checkbox','<a href="#"><input type="checkbox" aria-label="c"></a>',N);
p('button > span tabindex -1','<button><span tabindex="-1">x</span></button>',N);
p('button > disabled button','<button>x<button disabled>y</button></button>',N);
p('link > details summary','<a href="#">x<details><summary>s</summary></details></a>',N);
p('role link > role button','<span role="link" tabindex="0">x<span role="button" tabindex="-1">y</span></span>',N);
p('role=option > checkbox','<div role="listbox" aria-label="l"><div role="option" aria-selected="false"><input type="checkbox" aria-label="c"></div></div>',N);
p('role=tab > close button','<div role="tablist"><div role="tab" aria-selected="true">T <button aria-label="close">x</button></div></div>',N);
p('menuitem > a','<div role="menu"><div role="menuitem"><a href="#">x</a></div></div>',N);
p('row > button (grid)','<div role="grid"><div role="row"><div role="gridcell"><button>x</button></div></div></div>',N);
p('treeitem > a','<ul role="tree" aria-label="t"><li role="treeitem" aria-selected="false"><a href="#">x</a></li></ul>',N);
p('label > input', '<label>Name <input></label>',N);
p('summary > a', '<details><summary>S <a href="#">link</a></summary>x</details>',N);
p('a with aria-hidden child button', '<a href="#">x<span aria-hidden="true"><button tabindex="-1">y</button></span></a>',N);
p('button role=none? > a', '<button role="none" tabindex="-1"><a href="#">x</a></button>',N);
p('a > img usemap? ', '<a href="#"><video controls></video></a>',N);
p('button > iframe', '<button><iframe title="f" src="about:blank"></iframe></button>',N);
p('button > [contenteditable]', '<button><span contenteditable="true">x</span></button>',N);
p('a no href > button', '<a><button>x</button></a>',N);
p('switch > a', '<div role="switch" aria-checked="false" tabindex="0"><a href="#">x</a></div>',N);
p('progressbar > a', '<div role="progressbar"><a href="#">x</a></div>',N);
p('img > a', '<div role="img" aria-label="x"><a href="#">x</a></div>',N);
p('separator focusable? > a', '<div role="separator"><a href="#">x</a></div>',N);
p('meter > a', '<meter value="0.5"><a href="#">x</a></meter>',N);
p('option native > ', '<select><option>x</option></select>',N);
