const p=require('./h');
const V=['aria-valid-attr-value','aria-allowed-attr','aria-valid-attr','aria-required-attr','aria-conditional-attr'];
p('aria-checked mixed on checkbox','<div role="checkbox" aria-checked="MIXED" tabindex="0">x</div>',V);
p('aria-checked mixed on radio','<div role="radio" aria-checked="mixed" tabindex="0">x</div>',V);
p('aria-current TRUE','<a href="#" aria-current="Page">x</a>',V);
p('aria-current empty','<a href="#" aria-current="">x</a>',V);
p('aria-invalid spelling','<input aria-label="x" aria-invalid="spelling">',V);
p('aria-invalid garbage','<input aria-label="x" aria-invalid="yes">',V);
p('aria-haspopup Menu','<button aria-haspopup="Menu">x</button>',V);
p('aria-level 0','<div role="heading" aria-level="0">x</div>',V);
p('aria-level 1.5','<div role="heading" aria-level="1.5">x</div>',V);
p('aria-level +2','<div role="heading" aria-level="+2">x</div>',V);
p('aria-level " 2 "','<div role="heading" aria-level=" 2 ">x</div>',V);
p('aria-valuenow 1e2','<div role="slider" aria-label="v" aria-valuenow="1e2" tabindex="0"></div>',V);
p('aria-valuenow .5','<div role="slider" aria-label="v" aria-valuenow=".5" tabindex="0"></div>',V);
p('aria-valuenow empty','<div role="slider" aria-label="v" aria-valuenow="" tabindex="0"></div>',V);
p('aria-posinset -1','<div role="listbox" aria-label="l"><div role="option" aria-selected="false" aria-posinset="1" aria-setsize="-1">x</div></div>',V);
p('aria-colcount -1','<div role="grid" aria-colcount="-1"><div role="row"><div role="gridcell">x</div></div></div>',V);
p('aria-rowindex 0','<table><tr aria-rowindex="0"><td>x</td></tr></table>',V);
p('aria-controls empty-ish','<button aria-controls=" ">x</button>',V);
p('aria-controls missing','<button aria-controls="nope" aria-expanded="false">x</button>',V);
p('aria-activedescendant missing','<div role="listbox" tabindex="0" aria-label="l" aria-activedescendant="nope"><div role="option" aria-selected="false">x</div></div>',V);
p('aria-describedby missing','<button aria-describedby="nope">x</button>',V);
p('aria-errormessage missing w/o invalid','<input aria-label="x" aria-errormessage="nope">',V);
p('aria-relevant "additions text"','<div aria-live="polite" aria-relevant="additions text">x</div>',V);
p('aria-relevant "all additions"','<div aria-live="polite" aria-relevant="all additions">x</div>',V);
p('aria-relevant "Additions"','<div aria-live="polite" aria-relevant="Additions">x</div>',V);
p('aria-dropeffect','<div aria-dropeffect="copy move">x</div>',V);
p('aria-sort on columnheader','<table><tr><th aria-sort="ascending">x</th></tr></table>',V);
p('aria-sort on td','<table><tr><td aria-sort="ascending">x</td></tr></table>',V);
p('aria-autocomplete Both','<input role="combobox" aria-expanded="false" aria-label="x" aria-autocomplete="Both">',V);
p('aria-orientation on scrollbar','<div role="scrollbar" aria-controls="c" aria-valuenow="1" aria-orientation="vertical"></div><div id="c"></div>',V);
p('aria-pressed on input type=button','<input type="button" value="b" aria-pressed="true">',V);
p('aria-expanded on a','<a href="#" aria-expanded="false">x</a>',V);
p('aria-selected on tr (row in table)','<table><tr aria-selected="true"><td>x</td></tr></table>',V);
p('aria-required on input checkbox','<input type="checkbox" aria-label="x" aria-required="true">',V);
p('aria-checked on input checkbox','<input type="checkbox" aria-label="x" aria-checked="true">',V);
p('aria-readonly on checkbox role','<div role="checkbox" aria-checked="false" aria-readonly="true" tabindex="0">x</div>',V);
p('aria-placeholder on input','<input aria-label="x" aria-placeholder="y">',V);
p('aria-valuetext on progress','<progress aria-label="p" value="1" max="2" aria-valuetext="half"></progress>',V);
p('aria-multiselectable on select','<select multiple aria-label="x" aria-multiselectable="true"><option>a</option></select>',V);
p('aria-owns on input','<input aria-label="x" aria-owns="z"><div id="z"></div>',V);
p('aria-label on td','<table><tr><td aria-label="x">x</td></tr></table>',V);
p('aria-braillelabel','<button aria-braillelabel="btn">x</button>',V);
p('aria-description','<button aria-description="desc">x</button>',V);
p('aria-details multiple ids','<button aria-details="a b">x</button><div id="a"></div><div id="b"></div>',V);
