const p=require('./h');
const V=['aria-allowed-attr'];
p('aria-sort on td','<table><tr><td aria-sort="ascending">x</td></tr></table>',V);
p('aria-sort on div role=cell','<div role="table"><div role="row"><div role="cell" aria-sort="ascending">x</div></div></div>',V);
p('aria-sort on div','<div aria-sort="ascending">x</div>',V);
p('aria-checked on button','<button aria-checked="true">x</button>',V);
p('aria-checked on td','<table><tr><td aria-checked="true">x</td></tr></table>',V);
p('aria-selected on li','<ul><li aria-selected="true">x</li></ul>',V);
p('aria-valuenow on h1','<h1 aria-valuenow="3">x</h1>',V);
p('aria-expanded on td','<table><tr><td aria-expanded="true">x</td></tr></table>',V);
p('aria-expanded on th','<table><tr><th aria-expanded="true">x</th></tr></table>',V);
p('aria-level on p','<p aria-level="2">x</p>',V);
p('aria-multiline on input', '<input aria-label="x" aria-multiline="true">',V);
p('aria-required on div role=button','<div role="button" tabindex="0" aria-required="true">x</div>',V);
p('aria-checked on role switch','<div role="switch" tabindex="0" aria-checked="true">x</div>',V);
p('aria-pressed on role=link','<a href="#" aria-pressed="true">x</a>',V);
p('aria-selected on button','<button aria-selected="true">x</button>',V);
p('aria-posinset on li','<ul><li aria-posinset="1" aria-setsize="3">x</li></ul>',V);
p('aria-haspopup on div','<div aria-haspopup="true">x</div>',V);
