const p=require('./h');
const R=['aria-required-children','aria-required-parent'];
p('list via aria-owns','<div role="list" aria-owns="i1"></div><div id="i1" role="listitem">a</div>',R);
p('listitem owned by list but DOM-nested in other','<div role="list" aria-owns="i1"></div><div role="tree"><div id="i1" role="listitem">a</div></div>',R);
p('tablist with tabs inside generic wrapper','<div role="tablist"><div><div role="tab" aria-selected="true">a</div></div></div>',R);
p('tablist with tab inside role=none ul','<div role="tablist"><ul role="none"><li role="none"><a role="tab" href="#" aria-selected="true">a</a></li></ul></div>',R);
p('menu with group > menuitem','<div role="menu"><div role="group"><div role="menuitem">a</div></div></div>',R);
p('menu with separator only + menuitem','<div role="menu"><div role="separator"></div><div role="menuitem">a</div></div>',R);
p('row in rowgroup in grid','<div role="grid"><div role="rowgroup"><div role="row"><div role="gridcell">a</div></div></div></div>',R);
p('row in grid directly via table element','<table role="grid"><tbody><tr><td>a</td></tr></tbody></table>',R);
p('row in table (native)','<table><tr><td>a</td></tr></table>',R);
p('cell in row in table w/ display contents','<div role="table"><div role="row" style="display:contents"><div role="cell">a</div></div></div>',R);
p('listbox with options inside group','<div role="listbox" aria-label="x"><div role="group" aria-label="g"><div role="option" aria-selected="false">a</div></div></div>',R);
p('combobox no popup (1.2)','<input role="combobox" aria-expanded="false" aria-label="x">',R);
p('tree with group nested','<ul role="tree" aria-label="t"><li role="treeitem" aria-expanded="true">a<ul role="group"><li role="treeitem">b</li></ul></li></ul>',R);
p('radiogroup empty','<div role="radiogroup" aria-label="r"></div>',R);
p('feed with article','<div role="feed"><article>a</article></div>',R);
p('menubar with menuitem in li role none','<ul role="menubar"><li><a role="menuitem" href="#">a</a></li></ul>',R);
p('list with li role none? ','<ul><li role="none">a</li></ul>',R);
p('listitem in ul role=list','<ul role="list"><li>x</li></ul>',R);
p('tab in tablist via aria-busy','<div role="tablist" aria-busy="true"></div>',R);
p('option inside select optgroup','<select aria-label="x"><optgroup label="g"><option>a</option></optgroup></select>',R);
p('treeitem inside group inside tree','<div role="tree" aria-label="t"><div role="group"><div role="treeitem" aria-selected="false">a</div></div></div>',R);
p('menuitem inside menu via slot? n/a; menuitemradio in group in menubar','<div role="menubar"><div role="group"><div role="menuitemradio" aria-checked="false">a</div></div></div>',R);
p('columnheader in row in grid','<div role="grid"><div role="row"><div role="columnheader">h</div></div></div>',R);
p('gridcell inside row inside treegrid','<div role="treegrid"><div role="row"><div role="gridcell">a</div></div></div>',R);
p('row directly in table w/ thead tr native','<table><thead><tr role="row"><th>h</th></tr></thead></table>',R);
p('tab in tablist with aria-owns duplicates', '<div role="tablist" aria-owns="t1"><div role="tab" id="t1" aria-selected="true">a</div></div>',R);
p('aria-owns references ancestor (cycle)', '<div role="list" id="L"><div role="listitem" aria-owns="L">a</div></div>',R);
