'use strict';

/**
 * Build a standalone browser bundle (surea11y.browser.js, at the package
 * root).
 *
 * The bundle carries English only. Every other locale is emitted beside it as
 * surea11y.i18n.<locale>.js, which a page loads with a second <script> tag.
 * That is why this script generates its own English-only core in memory
 * rather than reading the shipped src/core.js: the in-page runner keeps its
 * message table inside the function body (it is serialized into the page by
 * the bindings, so it cannot reference anything outside itself), so the only
 * way to give the bundle a smaller table is to generate it with one.
 *
 * A generated core has three sections (see scripts/build-core.js):
 *   1. A Node-only section (`RULE_IMPLS` built from `require()` calls,
 *      catalog helpers, `runDomRulesInPage`) -- not usable outside Node.
 *   2. `runa11yCoreInPage` -- deliberately self-contained (no free vars: its
 *      own private copy of the rule catalog, `runCore`, and every helper it
 *      needs, all inlined inside the function body). This is the only part
 *      of the engine safe to run in a page realm with no bundler.
 *   3. `runa11yCoreAcrossFrames`/`a11yCoreEnableFrameResponder` -- also
 *      self-contained, but as a pair wrapped in their own shared IIFE, not
 *      as a single function. Left out of this bundle deliberately: it
 *      roughly doubles payload size for a cooperative-postMessage feature
 *      that itself requires the *embedded* page to also load surea11y and
 *      opt in, which isn't the common "drop one script tag" case this
 *      bundle targets. Node/bundler consumers who need it already have it
 *      via `require('@surea11y/core')`.
 *
 * This script locates section 2 via the same marker comments build-core.js
 * writes around it, and wraps it in a small IIFE that assigns a single
 * global, `window.a11ycore`, instead of the `module.exports` src/core.js
 * uses -- the actual reason src/core.js itself can't just be dropped into a
 * plain <script> tag as-is.
 */

const fs = require('fs');
const path = require('path');

const {
  loadRuleModules,
  loadAllTranslations,
  loadCompositeRulesCatalog,
  generateCore
} = require('./build-core.js');

const ROOT_DIR = path.join(__dirname, '..');
const OUTPUT_FILE = path.join(ROOT_DIR, 'surea11y.browser.js');
const localeFileFor = (locale) => path.join(ROOT_DIR, `surea11y.i18n.${locale}.js`);

const IN_PAGE_START_MARKER =
  'function runa11yCoreInPage(pageUrl, contextSelector, engineOptions, runOnly) {';
const CROSS_FRAME_BANNER =
  '// SELF-CONTAINED cross-frame scanning for the "plain script injection"';

function extractInPageRunnerSource(coreSource) {
  const start = coreSource.indexOf(IN_PAGE_START_MARKER);
  const end = coreSource.indexOf(CROSS_FRAME_BANNER);

  if (start === -1 || end === -1 || end <= start) {
    throw new Error(
      'build-browser: could not locate runa11yCoreInPage in src/core.js -- ' +
        "has scripts/build-core.js's generated output shape changed? " +
        'Expected to find both a literal "' +
        IN_PAGE_START_MARKER +
        '" and a ' +
        'later "' +
        CROSS_FRAME_BANNER +
        '" marker comment.'
    );
  }

  return coreSource
    .slice(start, end)
    .replace(/\n\/\/ =+\s*$/, '') // trailing "// ===...=" divider line preceding the next section's banner
    .trimEnd();
}

function readEngineConstants(coreSource) {
  const tagMatch = coreSource.match(/^const ENGINE_TAG = (".*");$/m);
  const versionMatch = coreSource.match(/^const SCHEMA_VERSION = (".*");$/m);

  if (!tagMatch || !versionMatch) {
    throw new Error('build-browser: could not read ENGINE_TAG/SCHEMA_VERSION from src/core.js');
  }

  return { engineTag: tagMatch[1], schemaVersion: versionMatch[1] };
}

function generateBrowserBundle(coreSource) {
  const inPageRunnerSource = extractInPageRunnerSource(coreSource);
  const { engineTag, schemaVersion } = readEngineConstants(coreSource);

  return `/**
 * @surea11y/core -- standalone browser bundle.
 *
 * Auto-generated by scripts/build-browser.js from src/core.js. Do not edit
 * this file by hand -- change the rule sources under src/checks and run
 * "npm run build" instead.
 *
 * Loading this file directly (e.g. via a <script> tag, with no bundler or
 * module loader) defines a single global, window.a11ycore, exposing the
 * engine's in-page scan function. See README.md's "Standalone browser
 * bundle" section and docs/INTEGRATION.md for usage and its one limitation
 * (no cross-frame scanning -- use the npm package directly for that).
 */
(function (global) {
  'use strict';

${inPageRunnerSource}

  // Locales registered by a surea11y.i18n.<locale>.js side file. The runner
  // keeps its own table inside its body, so a late-loaded dictionary can only
  // reach it as data on engineOptions -- this wrapper is what passes it.
  const registered = Object.create(null);

  function withRegisteredMessages(engineOptions) {
    const options = engineOptions && typeof engineOptions === 'object' ? engineOptions : {};
    if (Object.keys(registered).length === 0) return options;

    return Object.assign({}, options, {
      messages: Object.assign({}, registered, options.messages)
    });
  }

  global.a11ycore = {
    ENGINE_TAG: ${engineTag},
    SCHEMA_VERSION: ${schemaVersion},
    registerMessages: function (locale, messages) {
      if (typeof locale !== 'string' || !locale.trim()) return;
      if (!messages || typeof messages !== 'object') return;
      registered[locale.trim()] = messages;
    },
    runa11yCoreInPage: function (pageUrl, contextSelector, engineOptions, runOnly) {
      return runa11yCoreInPage(
        pageUrl,
        contextSelector,
        withRegisteredMessages(engineOptions),
        runOnly
      );
    }
  };
})(typeof window !== 'undefined' ? window : this);
`;
}

// Translations come from contributors, so a value could contain "</script>".
// Harmless while the file is loaded by src, fatal the moment someone inlines
// it -- the same reason src/report.js neutralizes '<' in its embedded JSON.
function jsonForScript(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

function generateLocaleSideFile(locale, dict) {
  return `/* SPDX-License-Identifier: MPL-2.0 */

/**
 * @surea11y/core -- ${locale} messages for the standalone browser bundle.
 *
 * Auto-generated by scripts/build-browser.js. Load it after
 * surea11y.browser.js, then scan with { locale: '${locale}' }:
 *
 *   <script src="surea11y.browser.js"></script>
 *   <script src="surea11y.i18n.${locale}.js"></script>
 */
(function (global) {
  'use strict';

  if (!global.a11ycore || typeof global.a11ycore.registerMessages !== 'function') {
    throw new Error(
      'surea11y.i18n.${locale}.js: load surea11y.browser.js first.'
    );
  }

  global.a11ycore.registerMessages(${jsonForScript(locale)}, ${jsonForScript(dict)});
})(typeof window !== 'undefined' ? window : this);
`;
}

function main() {
  const i18nAll = loadAllTranslations();
  const knownLocales = Object.keys(i18nAll);

  const coreSource = generateCore(
    loadRuleModules(),
    { en: i18nAll.en },
    loadCompositeRulesCatalog(),
    knownLocales
  );
  const bundle = generateBrowserBundle(coreSource);

  fs.writeFileSync(OUTPUT_FILE, `/* SPDX-License-Identifier: MPL-2.0 */\n\n${bundle}`, 'utf8');
  // eslint-disable-next-line no-console
  console.log(
    `[build-browser] wrote ${path.relative(ROOT_DIR, OUTPUT_FILE)} (${(bundle.length / 1024).toFixed(0)} KB)`
  );

  for (const locale of knownLocales.filter((l) => l !== 'en')) {
    const source = generateLocaleSideFile(locale, i18nAll[locale]);
    fs.writeFileSync(localeFileFor(locale), source, 'utf8');
    // eslint-disable-next-line no-console
    console.log(
      `[build-browser] wrote ${path.relative(ROOT_DIR, localeFileFor(locale))} (${(source.length / 1024).toFixed(0)} KB)`
    );
  }
}

module.exports = {
  extractInPageRunnerSource,
  readEngineConstants,
  generateBrowserBundle,
  generateLocaleSideFile
};

if (require.main === module) {
  main();
}
