'use strict';

/**
 * DOM-rules based accessibility core (generated from src/rules)
 *
 * Do not edit this file directly.
 * Edit rules in src/rules and run: npm run build
 */

const ENGINE_TAG = 'a11yCore';

const RULE_DEFS = [
  {
    "ruleId": "a11yCore-area-alt-present",
    "title": "Image map areas must have alt text",
    "description": "Ensures <area href> elements in image maps provide a non-empty alt text alternative.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "links",
      "imagemap",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-canvas-text-alternative",
    "title": "Canvas must have a text alternative",
    "description": "Ensures <canvas> elements provide fallback content or an accessible name as a text alternative mechanism.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "canvas",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-form-control-accessible-name",
    "title": "Form controls must have an accessible name",
    "description": "Fails when an applicable form control has no accessible name (e.g., label, aria-label, aria-labelledby).",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag131",
      "wcag412",
      "forms",
      "atomic",
      "a11yCore"
    ],
    "wcagSc": [
      "1.3.1",
      "4.1.2"
    ],
    "defaultSeverity": "critical",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-form-control-explicit-label",
    "title": "Form controls should have an explicit <label> element",
    "description": "Fails when an applicable form control is not associated with a <label> element (wrapping or for/id).",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag131",
      "forms",
      "atomic",
      "a11yCore"
    ],
    "wcagSc": [
      "1.3.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-img-alt-attr-present",
    "title": "Images must have an alt attribute",
    "description": "Ensures <img> elements include an alt attribute as a text alternative mechanism.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-img-alt-empty",
    "title": "Empty alt text requires verification",
    "description": "Flags <img> elements with empty alt text for manual verification (decorative vs informative).",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "atomic",
      "manual",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "moderate",
    "category": "perceivable",
    "type": "manual",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "a11yCore-img-alt-functional-name",
    "title": "Image-only controls must have an accessible name",
    "description": "Ensures links and buttons that are represented only by an image provide a non-empty accessible name.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "links",
      "forms",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-input-image-accessible-name",
    "title": "Image inputs must have an accessible name",
    "description": "Ensures <input type='image'> elements have a non-empty accessible name.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "forms",
      "images",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-links-target-blank-noopener",
    "title": "Links that open in a new tab should use rel=\"noopener\"",
    "description": "Ensures links with target=\"_blank\" mitigate reverse tabnabbing risks.",
    "helpUrl": null,
    "tags": [
      "best-practice",
      "links",
      "a11yCore"
    ],
    "wcagSc": [],
    "defaultSeverity": "minor",
    "category": "robust",
    "type": "automatic",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "manual-review",
    "title": "Manual review: keyboard navigation and focus order",
    "description": "Flags that a manual review of keyboard navigation and focus order is required.",
    "helpUrl": null,
    "tags": [
      "manual",
      "a11yCore"
    ],
    "wcagSc": [],
    "defaultSeverity": "moderate",
    "category": "operable",
    "type": "manual",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "a11yCore-nontext-equivalent-alternative-manual",
    "title": "Non-text alternatives must be equivalent (manual)",
    "description": "Flags non-text content that has some text alternative mechanism so a human can verify equivalence per WCAG 1.1.1.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "manual",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "minor",
    "category": "perceivable",
    "type": "manual",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "a11yCore-svg-role-img-name",
    "title": "SVG images must have an accessible name",
    "description": "Ensures inline SVG graphics exposed as images provide a non-empty accessible name.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "svg",
      "images",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  }
];

function normalizeRuleResult(def, raw) {
  const out = raw && typeof raw === 'object' ? { ...raw } : {};

  // rule id
  out.ruleId = out.ruleId || def.ruleId;

  // outcome
  if (!VALID_OUTCOMES.includes(out.outcome)) {
    out.outcome = 'cantTell';
  }

  // severity
  out.severity = out.severity || def.defaultSeverity || 'moderate';

  // confidence
  const defConfidence = def.defaultConfidence || 'medium';
  let conf = raw && raw.confidence;
  if (!VALID_CONFIDENCE.includes(conf)) {
    conf = defConfidence;
  }
  out.confidence = conf;

  // type (copied from definition, not from raw)
  out.type = def.type || 'automatic';

  // occurrences
  const occ = Array.isArray(out.occurrences) ? out.occurrences : [];
  out.occurrences = occ.map((item) => {
    const o = item && typeof item === 'object' ? { ...item } : {};
    if (typeof o.selector !== 'string') o.selector = '';
    if (typeof o.summary !== 'string') o.summary = '';
    if (typeof o.html !== 'string') o.html = '';
    return o;
  });

  // error, if any
  if (raw && raw.error) {
    out.error = String(raw.error);
  }

  return out;
}

function getRuleDefById(ruleId) {
  return RULE_DEFS.find((r) => r.ruleId === ruleId) || null;
}

function ruleMatchesRunOnly(rule, runOnly) {
  if (!runOnly || runOnly.type !== 'tag') return true;
  const values = Array.isArray(runOnly.values) ? runOnly.values : [];
  if (!values.length) return true;
  const tags = Array.isArray(rule.tags) ? rule.tags : [];
  return tags.some((t) => values.includes(t));
}

function getRulesCatalog() {
  return RULE_DEFS.map((r) => ({
    ruleId: r.ruleId,
    title: r.title,
    description: r.description,
    helpUrl: r.helpUrl,
    tags: Array.isArray(r.tags) ? r.tags.slice() : [],
    wcagSc: Array.isArray(r.wcagSc) ? r.wcagSc.slice() : [],
    defaultSeverity: r.defaultSeverity || 'moderate',
    category: r.category || null,
    type: r.type || 'automatic',
    defaultConfidence: r.defaultConfidence || 'medium'
  }));
}

function getRulesForRunOnly(runOnly) {
  return RULE_DEFS
    .filter((r) => ruleMatchesRunOnly(r, runOnly))
    .map((r) => ({
      ruleId: r.ruleId,
      title: r.title,
      description: r.description,
      helpUrl: r.helpUrl,
      tags: Array.isArray(r.tags) ? r.tags.slice() : [],
      wcagSc: Array.isArray(r.wcagSc) ? r.wcagSc.slice() : [],
      defaultSeverity: r.defaultSeverity || 'moderate',
      category: r.category || null,
      type: r.type || 'automatic',
      defaultConfidence: r.defaultConfidence || 'medium'
    }));
}

/**
 * Runs DOM based rules inside the page and returns a compact native result.
 * This function is executed inside the browser context via page.evaluate.
 */
function runa11yCoreInPage(pageUrl, contextSelector, engineOptions, runOnly) {
  const ENGINE_TAG = 'a11yCore'; // make ENGINE_TAG local for page.evaluate
  const RULE_DEFS = [
  {
    "ruleId": "a11yCore-area-alt-present",
    "title": "Image map areas must have alt text",
    "description": "Ensures <area href> elements in image maps provide a non-empty alt text alternative.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "links",
      "imagemap",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-canvas-text-alternative",
    "title": "Canvas must have a text alternative",
    "description": "Ensures <canvas> elements provide fallback content or an accessible name as a text alternative mechanism.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "canvas",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-form-control-accessible-name",
    "title": "Form controls must have an accessible name",
    "description": "Fails when an applicable form control has no accessible name (e.g., label, aria-label, aria-labelledby).",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag131",
      "wcag412",
      "forms",
      "atomic",
      "a11yCore"
    ],
    "wcagSc": [
      "1.3.1",
      "4.1.2"
    ],
    "defaultSeverity": "critical",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-form-control-explicit-label",
    "title": "Form controls should have an explicit <label> element",
    "description": "Fails when an applicable form control is not associated with a <label> element (wrapping or for/id).",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag131",
      "forms",
      "atomic",
      "a11yCore"
    ],
    "wcagSc": [
      "1.3.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-img-alt-attr-present",
    "title": "Images must have an alt attribute",
    "description": "Ensures <img> elements include an alt attribute as a text alternative mechanism.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-img-alt-empty",
    "title": "Empty alt text requires verification",
    "description": "Flags <img> elements with empty alt text for manual verification (decorative vs informative).",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "atomic",
      "manual",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "moderate",
    "category": "perceivable",
    "type": "manual",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "a11yCore-img-alt-functional-name",
    "title": "Image-only controls must have an accessible name",
    "description": "Ensures links and buttons that are represented only by an image provide a non-empty accessible name.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "images",
      "links",
      "forms",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-input-image-accessible-name",
    "title": "Image inputs must have an accessible name",
    "description": "Ensures <input type='image'> elements have a non-empty accessible name.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "forms",
      "images",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  },
  {
    "ruleId": "a11yCore-links-target-blank-noopener",
    "title": "Links that open in a new tab should use rel=\"noopener\"",
    "description": "Ensures links with target=\"_blank\" mitigate reverse tabnabbing risks.",
    "helpUrl": null,
    "tags": [
      "best-practice",
      "links",
      "a11yCore"
    ],
    "wcagSc": [],
    "defaultSeverity": "minor",
    "category": "robust",
    "type": "automatic",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "manual-review",
    "title": "Manual review: keyboard navigation and focus order",
    "description": "Flags that a manual review of keyboard navigation and focus order is required.",
    "helpUrl": null,
    "tags": [
      "manual",
      "a11yCore"
    ],
    "wcagSc": [],
    "defaultSeverity": "moderate",
    "category": "operable",
    "type": "manual",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "a11yCore-nontext-equivalent-alternative-manual",
    "title": "Non-text alternatives must be equivalent (manual)",
    "description": "Flags non-text content that has some text alternative mechanism so a human can verify equivalence per WCAG 1.1.1.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "manual",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "minor",
    "category": "perceivable",
    "type": "manual",
    "defaultConfidence": "medium"
  },
  {
    "ruleId": "a11yCore-svg-role-img-name",
    "title": "SVG images must have an accessible name",
    "description": "Ensures inline SVG graphics exposed as images provide a non-empty accessible name.",
    "helpUrl": null,
    "tags": [
      "wcag2a",
      "wcag111",
      "svg",
      "images",
      "a11yCore"
    ],
    "wcagSc": [
      "1.1.1"
    ],
    "defaultSeverity": "serious",
    "category": "perceivable",
    "type": "automatic",
    "defaultConfidence": "high"
  }
];

  const VALID_OUTCOMES = ['fail', 'pass', 'cantTell', 'notApplicable'];
  const VALID_CONFIDENCE = ['high', 'medium', 'low'];

  const RULE_IMPLS = {
    "a11yCore-area-alt-present": function runInPage(ctx) {
      // SAFETY: This function runs in the page context via serialization. Do not capture outer scope.
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot = root || document;
    
      const queryAll =
          helpers && helpers.queryAll
              ? helpers.queryAll
              : (sel) => {
                if (!safeRoot || !safeRoot.querySelectorAll) return [];
                try {
                  return Array.from(safeRoot.querySelectorAll(sel));
                } catch {
                  return [];
                }
              };
    
      const queryAllSmart =
          helpers && helpers.queryAllSmart
              ? helpers.queryAllSmart
              : null;
    
      const query =
          queryAllSmart
              ? (sel) => {
                try {
                  return Array.from(queryAllSmart(sel) || []);
                } catch {
                  return queryAll(sel);
                }
              }
              : queryAll;
    
      const getOuterHtmlSnippet =
          helpers && helpers.getOuterHtmlSnippet
              ? helpers.getOuterHtmlSnippet
              : (el) => {
                if (!el || typeof el !== 'object') return '';
                return el.outerHTML || '';
              };
    
      const buildSimpleSelector =
          helpers && helpers.buildSimpleSelector
              ? helpers.buildSimpleSelector
              : (el) => {
                if (!el || typeof el !== 'object') return 'html';
                const tag = (el.tagName || 'html').toLowerCase();
                const id = el.id ? `#${el.id}` : '';
                const cls = el.classList && el.classList.length
                    ? '.' + Array.from(el.classList).slice(0, 2).join('.')
                    : '';
                return `${tag}${id}${cls}` || 'html';
              };
    
      const getAriaLabel = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('aria-label');
        return (v || '').trim();
      };
    
      const getTitleAttr = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('title');
        return (v || '').trim();
      };
    
      const getLabelledByText = (el) => {
        if (!el || !el.getAttribute) return '';
        const ids = (el.getAttribute('aria-labelledby') || '').trim();
        if (!ids) return '';
        const parts = ids.split(/\s+/).filter(Boolean);
        const texts = [];
        for (const idref of parts) {
          const ref = safeRoot.getElementById ? safeRoot.getElementById(idref) : document.getElementById(idref);
          if (ref && ref.textContent) {
            const t = ref.textContent.trim();
            if (t) texts.push(t);
          }
        }
        return texts.join(' ').trim();
      };
    
      const isHiddenFromAT = (el) => {
        if (!el || !el.getAttribute) return false;
        const ariaHidden = (el.getAttribute('aria-hidden') || '').toLowerCase();
        return ariaHidden === 'true';
      };
    
    
      const areas = query('area[href]').filter((el) => el && el.tagName && !isHiddenFromAT(el));
    
      if (!areas.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'serious',
          occurrences: []
        };
      }
    
      const occurrencesFail = [];
    
      for (const area of areas) {
        const alt = area.getAttribute ? area.getAttribute('alt') : null;
        const altTrim = (alt || '').trim();
    
        if (alt === null || altTrim === '') {
          let selector = 'html';
          try { selector = buildSimpleSelector(area); } catch {}
          const html = getOuterHtmlSnippet(area);
    
          occurrencesFail.push({
            selector,
            html,
            summary: 'Image map area is missing a non-empty alt text alternative.',
            hint: 'Provide an alt attribute that describes the purpose/destination of the hotspot.'
          });
        }
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'serious',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    
    },
    "a11yCore-canvas-text-alternative": function runInPage(ctx) {
      // SAFETY: This function runs in the page context via serialization. Do not capture outer scope.
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot = root || document;
    
      const queryAll =
          helpers && helpers.queryAll
              ? helpers.queryAll
              : (sel) => {
                if (!safeRoot || !safeRoot.querySelectorAll) return [];
                try {
                  return Array.from(safeRoot.querySelectorAll(sel));
                } catch {
                  return [];
                }
              };
    
      const queryAllSmart =
          helpers && helpers.queryAllSmart
              ? helpers.queryAllSmart
              : null;
    
      const query =
          queryAllSmart
              ? (sel) => {
                try {
                  return Array.from(queryAllSmart(sel) || []);
                } catch {
                  return queryAll(sel);
                }
              }
              : queryAll;
    
      const getOuterHtmlSnippet =
          helpers && helpers.getOuterHtmlSnippet
              ? helpers.getOuterHtmlSnippet
              : (el) => {
                if (!el || typeof el !== 'object') return '';
                return el.outerHTML || '';
              };
    
      const buildSimpleSelector =
          helpers && helpers.buildSimpleSelector
              ? helpers.buildSimpleSelector
              : (el) => {
                if (!el || typeof el !== 'object') return 'html';
                const tag = (el.tagName || 'html').toLowerCase();
                const id = el.id ? `#${el.id}` : '';
                const cls = el.classList && el.classList.length
                    ? '.' + Array.from(el.classList).slice(0, 2).join('.')
                    : '';
                return `${tag}${id}${cls}` || 'html';
              };
    
      const getAriaLabel = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('aria-label');
        return (v || '').trim();
      };
    
      const getTitleAttr = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('title');
        return (v || '').trim();
      };
    
      const getLabelledByText = (el) => {
        if (!el || !el.getAttribute) return '';
        const ids = (el.getAttribute('aria-labelledby') || '').trim();
        if (!ids) return '';
        const parts = ids.split(/\s+/).filter(Boolean);
        const texts = [];
        for (const idref of parts) {
          const ref = safeRoot.getElementById ? safeRoot.getElementById(idref) : document.getElementById(idref);
          if (ref && ref.textContent) {
            const t = ref.textContent.trim();
            if (t) texts.push(t);
          }
        }
        return texts.join(' ').trim();
      };
    
      const isHiddenFromAT = (el) => {
        if (!el || !el.getAttribute) return false;
        const ariaHidden = (el.getAttribute('aria-hidden') || '').toLowerCase();
        return ariaHidden === 'true';
      };
    
    
      const canvases = query('canvas').filter((el) => el && el.tagName && !isHiddenFromAT(el));
    
      if (!canvases.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'serious',
          occurrences: []
        };
      }
    
      const occurrencesFail = [];
    
      for (const canvas of canvases) {
        const fallbackText = (canvas.textContent || '').trim();
    
        const name =
            getAriaLabel(canvas) ||
            getLabelledByText(canvas) ||
            getTitleAttr(canvas);
    
        if (!fallbackText && !name) {
          let selector = 'html';
          try { selector = buildSimpleSelector(canvas); } catch {}
          const html = getOuterHtmlSnippet(canvas);
    
          occurrencesFail.push({
            selector,
            html,
            summary: 'Canvas element has no text alternative.',
            hint: 'Provide fallback text content inside <canvas>…</canvas> or an accessible name via aria-label/aria-labelledby (or title as a fallback).'
          });
        }
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'serious',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    
    },
    "a11yCore-form-control-accessible-name": function runInPage(ctx) {
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot =
        root ||
        document.documentElement ||
        document.body ||
        document.querySelector('html') ||
        document;
    
      const queryAll =
        helpers && helpers.queryAll
          ? helpers.queryAll
          : (sel) => {
              if (!safeRoot || !safeRoot.querySelectorAll) return [];
              try {
                return Array.from(safeRoot.querySelectorAll(sel));
              } catch {
                return [];
              }
            };
    
      const queryAllSmart =
        helpers && typeof helpers.queryAllSmart === 'function'
          ? helpers.queryAllSmart
          : queryAll;
    
      const getOuterHtmlSnippet =
        helpers && helpers.getOuterHtmlSnippet
          ? helpers.getOuterHtmlSnippet
          : (el) => {
              if (!el || typeof el !== 'object') return '';
              try {
                const html = el.outerHTML || '';
                return html.length > 2000 ? html.slice(0, 2000) + '…' : html;
              } catch {
                return '';
              }
            };
    
      const buildSimpleSelector =
        helpers && helpers.buildSimpleSelector
          ? helpers.buildSimpleSelector
          : (el, fallbackTag) => {
              try {
                if (!el || typeof el !== 'object') return fallbackTag || 'html';
                const tag = el.tagName ? String(el.tagName).toLowerCase() : (fallbackTag || 'html');
                const getAttr = typeof el.getAttribute === 'function' ? el.getAttribute.bind(el) : null;
    
                if (getAttr) {
                  const idAttr = getAttr('id');
                  if (idAttr && idAttr.trim()) return tag + '#' + idAttr.trim();
    
                  const classAttr = getAttr('class') || '';
                  const cls = String(classAttr).split(/\s+/).filter(Boolean);
                  if (cls.length) return tag + '.' + cls[0];
    
                  const nameAttr = getAttr('name');
                  if (nameAttr && nameAttr.trim()) return tag + '[name="' + nameAttr.trim() + '"]';
                }
    
                return tag;
              } catch {
                return fallbackTag || 'html';
              }
            };
    
      const hasAccessibleName =
        helpers && typeof helpers.hasAccessibleName === 'function'
          ? helpers.hasAccessibleName
          : () => false;
    
      const allControlsRaw = queryAllSmart('input, textarea, select');
      const allControls = Array.isArray(allControlsRaw) ? allControlsRaw : [];
    
      const candidates = [];
      for (const el of allControls) {
        if (!el || typeof el !== 'object') continue;
    
        let type = '';
        try {
          if (typeof el.getAttribute === 'function') {
            const raw = el.getAttribute('type');
            type = raw == null ? '' : String(raw);
          }
        } catch {
          type = '';
        }
    
        const t = type.toLowerCase();
        if (t === 'hidden') continue;
        if (t === 'submit' || t === 'button' || t === 'reset' || t === 'image') continue;
    
        candidates.push(el);
      }
    
      if (!candidates.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: 'minor',
          occurrences: []
        };
      }
    
      const occurrencesFail = [];
    
      for (const el of candidates) {
        let hasName = false;
        try {
          hasName = !!hasAccessibleName(el);
        } catch {
          hasName = false;
        }
    
        if (hasName) continue;
    
        const fallbackTag = el && el.tagName ? String(el.tagName).toLowerCase() : 'html';
        const selector = buildSimpleSelector(el, fallbackTag);
        const html = getOuterHtmlSnippet(el);
    
        occurrencesFail.push({
          selector,
          html,
          summary: 'Form control has no accessible name.',
          hint: 'Provide an accessible name via a <label>, aria-label, or aria-labelledby.'
        });
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'critical',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    },
    "a11yCore-form-control-explicit-label": function runInPage(ctx) {
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot =
        root ||
        document.documentElement ||
        document.body ||
        document.querySelector('html') ||
        document;
    
      const queryAll =
        helpers && helpers.queryAll
          ? helpers.queryAll
          : (sel) => {
              if (!safeRoot || !safeRoot.querySelectorAll) return [];
              try {
                return Array.from(safeRoot.querySelectorAll(sel));
              } catch {
                return [];
              }
            };
    
      const queryAllSmart =
        helpers && typeof helpers.queryAllSmart === 'function'
          ? helpers.queryAllSmart
          : queryAll;
    
      const getOuterHtmlSnippet =
        helpers && helpers.getOuterHtmlSnippet
          ? helpers.getOuterHtmlSnippet
          : (el) => {
              if (!el || typeof el !== 'object') return '';
              try {
                const html = el.outerHTML || '';
                return html.length > 2000 ? html.slice(0, 2000) + '…' : html;
              } catch {
                return '';
              }
            };
    
      const buildSimpleSelector =
        helpers && helpers.buildSimpleSelector
          ? helpers.buildSimpleSelector
          : (el, fallbackTag) => {
              try {
                if (!el || typeof el !== 'object') return fallbackTag || 'html';
                const tag = el.tagName ? String(el.tagName).toLowerCase() : (fallbackTag || 'html');
                const getAttr = typeof el.getAttribute === 'function' ? el.getAttribute.bind(el) : null;
    
                if (getAttr) {
                  const idAttr = getAttr('id');
                  if (idAttr && idAttr.trim()) return tag + '#' + idAttr.trim();
    
                  const classAttr = getAttr('class') || '';
                  const cls = String(classAttr).split(/\s+/).filter(Boolean);
                  if (cls.length) return tag + '.' + cls[0];
    
                  const nameAttr = getAttr('name');
                  if (nameAttr && nameAttr.trim()) return tag + '[name="' + nameAttr.trim() + '"]';
                }
    
                return tag;
              } catch {
                return fallbackTag || 'html';
              }
            };
    
      function escapeAttrValue(value) {
        // Minimal escaping for use inside CSS attribute selectors with quotes.
        // If CSS.escape is available, use it for better correctness.
        try {
          if (typeof window !== 'undefined' && window.CSS && typeof window.CSS.escape === 'function') {
            return window.CSS.escape(value);
          }
        } catch {
          // ignore
        }
        return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
      }
    
      function hasExplicitLabel(el) {
        try {
          if (!el || typeof el !== 'object') return false;
    
          // Wrapped by a label (works across shadow boundaries within same tree)
          if (typeof el.closest === 'function') {
            const wrap = el.closest('label');
            if (wrap && typeof wrap.textContent === 'string' && wrap.textContent.trim()) return true;
          }
    
          // Associated label via for/id, scoped to the element's root (document or shadow root)
          const getAttr = typeof el.getAttribute === 'function' ? el.getAttribute.bind(el) : null;
          if (!getAttr) return false;
          const id = getAttr('id');
          if (!id || !String(id).trim()) return false;
    
          const rootNode = typeof el.getRootNode === 'function' ? el.getRootNode() : null;
          const scope = rootNode && typeof rootNode.querySelector === 'function' ? rootNode : document;
    
          const esc = escapeAttrValue(String(id).trim());
          let label = null;
          try {
            label = scope.querySelector('label[for="' + esc + '"]');
          } catch {
            // fallback without escaping
            try {
              label = scope.querySelector('label[for="' + String(id).trim() + '"]');
            } catch {
              label = null;
            }
          }
          if (label && typeof label.textContent === 'string' && label.textContent.trim()) return true;
    
          return false;
        } catch {
          return false;
        }
      }
    
      const allControlsRaw = queryAllSmart('input, textarea, select');
      const allControls = Array.isArray(allControlsRaw) ? allControlsRaw : [];
    
      const candidates = [];
      for (const el of allControls) {
        if (!el || typeof el !== 'object') continue;
    
        let type = '';
        try {
          if (typeof el.getAttribute === 'function') {
            const raw = el.getAttribute('type');
            type = raw == null ? '' : String(raw);
          }
        } catch {
          type = '';
        }
    
        const t = type.toLowerCase();
        if (t === 'hidden') continue;
        if (t === 'submit' || t === 'button' || t === 'reset' || t === 'image') continue;
    
        candidates.push(el);
      }
    
      if (!candidates.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: 'minor',
          occurrences: []
        };
      }
    
      const occurrencesFail = [];
    
      for (const el of candidates) {
        if (hasExplicitLabel(el)) continue;
    
        const fallbackTag = el && el.tagName ? String(el.tagName).toLowerCase() : 'html';
        const selector = buildSimpleSelector(el, fallbackTag);
        const html = getOuterHtmlSnippet(el);
    
        occurrencesFail.push({
          selector,
          html,
          summary: 'Form control has no explicit <label> element association.',
          hint: 'Associate a <label> by wrapping the control or using label[for] with a matching id.'
        });
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'serious',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    },
    "a11yCore-img-alt-attr-present": function runInPage(ctx) {
      // SAFETY: This function runs in the page context via serialization. Do not capture outer scope.
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot = root || document;
    
      const queryAll =
          helpers && helpers.queryAll
              ? helpers.queryAll
              : (sel) => {
                if (!safeRoot || !safeRoot.querySelectorAll) return [];
                try {
                  return Array.from(safeRoot.querySelectorAll(sel));
                } catch {
                  return [];
                }
              };
    
      const queryAllSmart =
          helpers && helpers.queryAllSmart
              ? helpers.queryAllSmart
              : null;
    
      const query =
          queryAllSmart
              ? (sel) => {
                try {
                  return Array.from(queryAllSmart(sel) || []);
                } catch {
                  return queryAll(sel);
                }
              }
              : queryAll;
    
      const getOuterHtmlSnippet =
          helpers && helpers.getOuterHtmlSnippet
              ? helpers.getOuterHtmlSnippet
              : (el) => {
                if (!el || typeof el !== 'object') return '';
                return el.outerHTML || '';
              };
    
      const buildSimpleSelector =
          helpers && helpers.buildSimpleSelector
              ? helpers.buildSimpleSelector
              : (el) => {
                if (!el || typeof el !== 'object') return 'html';
                const tag = (el.tagName || 'html').toLowerCase();
                const id = el.id ? `#${el.id}` : '';
                const cls = el.classList && el.classList.length
                    ? '.' + Array.from(el.classList).slice(0, 2).join('.')
                    : '';
                return `${tag}${id}${cls}` || 'html';
              };
    
      const getAriaLabel = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('aria-label');
        return (v || '').trim();
      };
    
      const getTitleAttr = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('title');
        return (v || '').trim();
      };
    
      const getLabelledByText = (el) => {
        if (!el || !el.getAttribute) return '';
        const ids = (el.getAttribute('aria-labelledby') || '').trim();
        if (!ids) return '';
        const parts = ids.split(/\s+/).filter(Boolean);
        const texts = [];
        for (const idref of parts) {
          const ref = safeRoot.getElementById ? safeRoot.getElementById(idref) : document.getElementById(idref);
          if (ref && ref.textContent) {
            const t = ref.textContent.trim();
            if (t) texts.push(t);
          }
        }
        return texts.join(' ').trim();
      };
    
      const isHiddenFromAT = (el) => {
        if (!el || !el.getAttribute) return false;
        const ariaHidden = (el.getAttribute('aria-hidden') || '').toLowerCase();
        return ariaHidden === 'true';
      };
    
    
      const imgs = query('img').filter((el) => el && el.tagName && !isHiddenFromAT(el));
    
      if (!imgs.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'serious',
          occurrences: []
        };
      }
    
      const occurrencesFail = [];
    
      for (const img of imgs) {
        // alt attribute is required by HTML for text alternatives; empty alt is allowed for decorative images.
        if (!img.hasAttribute || !img.hasAttribute('alt')) {
          let selector = 'html';
          try { selector = buildSimpleSelector(img); } catch {}
          const html = getOuterHtmlSnippet(img);
    
          occurrencesFail.push({
            selector,
            html,
            summary: 'Image is missing an alt attribute.',
            hint: 'Add an alt attribute. Use alt="" only when the image is purely decorative.'
          });
        }
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'serious',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    
    },
    "a11yCore-img-alt-empty": function runInPage(ctx) {
      const { document, root, helpers, rule } = ctx;
    
      const queryAll = helpers && helpers.queryAll
        ? helpers.queryAll
        : (sel) => {
          try {
            return Array.from((root || document).querySelectorAll(sel));
          } catch {
            return [];
          }
        };
    
      const getOuterHtmlSnippet = helpers && helpers.getOuterHtmlSnippet
        ? helpers.getOuterHtmlSnippet
        : (el) => (el && el.outerHTML) || '';
    
      const buildSimpleSelector = helpers && helpers.buildSimpleSelector
        ? helpers.buildSimpleSelector
        : (el, fallbackTag) => {
          try {
            if (!el || el.nodeType !== 1) return fallbackTag || '';
            if (el.id) return `#${el.id}`;
            const tag = (el.tagName || fallbackTag || '').toLowerCase();
            return tag || fallbackTag || '';
          } catch {
            return fallbackTag || '';
          }
        };
    
      const occurrences = [];
      const imgs = helpers.queryAllSmart ? helpers.queryAllSmart('img') : queryAll('img');
    
      for (const img of imgs) {
        if (!img || img.nodeType !== 1) continue;
    
        const ariaHidden = img.getAttribute('aria-hidden');
        if (ariaHidden === 'true') continue;
    
        const role = (img.getAttribute('role') || '').trim().toLowerCase();
        if (role === 'presentation' || role === 'none') continue;
    
        const alt = img.getAttribute('alt');
        if (alt === null) continue; // handled by img-alt-attr-present
    
        if (String(alt).trim() === '') {
          occurrences.push({
            selector: buildSimpleSelector(img, 'img'),
            html: getOuterHtmlSnippet(img),
            summary: 'Image has empty alt text (alt="").',
            hint: 'Confirm the image is decorative; otherwise provide a meaningful alt text.'
          });
        }
      }
    
      if (!imgs.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: 'minor',
          occurrences: []
        };
      }
    
      if (occurrences.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'cantTell',
          severity: rule.defaultSeverity || 'minor',
          occurrences
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    },
    "a11yCore-img-alt-functional-name": function runInPage(ctx) {
      // SAFETY: This function runs in the page context via serialization. Do not capture outer scope.
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot = root || document;
    
      const queryAll =
          helpers && helpers.queryAll
              ? helpers.queryAll
              : (sel) => {
                if (!safeRoot || !safeRoot.querySelectorAll) return [];
                try {
                  return Array.from(safeRoot.querySelectorAll(sel));
                } catch {
                  return [];
                }
              };
    
      const queryAllSmart =
          helpers && helpers.queryAllSmart
              ? helpers.queryAllSmart
              : null;
    
      const query =
          queryAllSmart
              ? (sel) => {
                try {
                  return Array.from(queryAllSmart(sel) || []);
                } catch {
                  return queryAll(sel);
                }
              }
              : queryAll;
    
      const getOuterHtmlSnippet =
          helpers && helpers.getOuterHtmlSnippet
              ? helpers.getOuterHtmlSnippet
              : (el) => {
                if (!el || typeof el !== 'object') return '';
                return el.outerHTML || '';
              };
    
      const buildSimpleSelector =
          helpers && helpers.buildSimpleSelector
              ? helpers.buildSimpleSelector
              : (el) => {
                if (!el || typeof el !== 'object') return 'html';
                const tag = (el.tagName || 'html').toLowerCase();
                const id = el.id ? `#${el.id}` : '';
                const cls = el.classList && el.classList.length
                    ? '.' + Array.from(el.classList).slice(0, 2).join('.')
                    : '';
                return `${tag}${id}${cls}` || 'html';
              };
    
      const getAriaLabel = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('aria-label');
        return (v || '').trim();
      };
    
      const getTitleAttr = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('title');
        return (v || '').trim();
      };
    
      const getLabelledByText = (el) => {
        if (!el || !el.getAttribute) return '';
        const ids = (el.getAttribute('aria-labelledby') || '').trim();
        if (!ids) return '';
        const parts = ids.split(/\s+/).filter(Boolean);
        const texts = [];
        for (const idref of parts) {
          const ref = safeRoot.getElementById ? safeRoot.getElementById(idref) : document.getElementById(idref);
          if (ref && ref.textContent) {
            const t = ref.textContent.trim();
            if (t) texts.push(t);
          }
        }
        return texts.join(' ').trim();
      };
    
      const isHiddenFromAT = (el) => {
        if (!el || !el.getAttribute) return false;
        const ariaHidden = (el.getAttribute('aria-hidden') || '').toLowerCase();
        return ariaHidden === 'true';
      };
    
    
      const controls = query('a,button').filter((el) => {
        if (!el || !el.tagName || isHiddenFromAT(el)) return false;
        // Ignore disabled buttons
        if (el.tagName.toLowerCase() === 'button' && el.disabled) return false;
    
        const imgs = el.querySelectorAll ? Array.from(el.querySelectorAll('img')) : [];
        if (imgs.length !== 1) return false;
    
        // Treat as "image-only" if there is no non-whitespace text content.
        const text = (el.textContent || '').trim();
        if (text) return false;
    
        return true;
      });
    
      if (!controls.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'serious',
          occurrences: []
        };
      }
    
      const occurrencesFail = [];
    
      for (const el of controls) {
        const img = el.querySelector ? el.querySelector('img') : null;
        const imgAlt = img && img.getAttribute ? (img.getAttribute('alt') || '').trim() : '';
    
        const name =
            getAriaLabel(el) ||
            getLabelledByText(el) ||
            imgAlt ||
            getTitleAttr(el);
    
        if (!name) {
          let selector = 'html';
          try { selector = buildSimpleSelector(el); } catch {}
          const html = getOuterHtmlSnippet(el);
    
          occurrencesFail.push({
            selector,
            html,
            summary: 'Image-only control has no accessible name.',
            hint: 'Provide a non-empty accessible name via the image alt text or aria-label/aria-labelledby on the control.'
          });
        }
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'serious',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    
    },
    "a11yCore-input-image-accessible-name": function runInPage(ctx) {
      // SAFETY: This function runs in the page context via serialization. Do not capture outer scope.
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot = root || document;
    
      const queryAll =
          helpers && helpers.queryAll
              ? helpers.queryAll
              : (sel) => {
                if (!safeRoot || !safeRoot.querySelectorAll) return [];
                try {
                  return Array.from(safeRoot.querySelectorAll(sel));
                } catch {
                  return [];
                }
              };
    
      const queryAllSmart =
          helpers && helpers.queryAllSmart
              ? helpers.queryAllSmart
              : null;
    
      const query =
          queryAllSmart
              ? (sel) => {
                try {
                  return Array.from(queryAllSmart(sel) || []);
                } catch {
                  return queryAll(sel);
                }
              }
              : queryAll;
    
      const getOuterHtmlSnippet =
          helpers && helpers.getOuterHtmlSnippet
              ? helpers.getOuterHtmlSnippet
              : (el) => {
                if (!el || typeof el !== 'object') return '';
                return el.outerHTML || '';
              };
    
      const buildSimpleSelector =
          helpers && helpers.buildSimpleSelector
              ? helpers.buildSimpleSelector
              : (el) => {
                if (!el || typeof el !== 'object') return 'html';
                const tag = (el.tagName || 'html').toLowerCase();
                const id = el.id ? `#${el.id}` : '';
                const cls = el.classList && el.classList.length
                    ? '.' + Array.from(el.classList).slice(0, 2).join('.')
                    : '';
                return `${tag}${id}${cls}` || 'html';
              };
    
      const getAriaLabel = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('aria-label');
        return (v || '').trim();
      };
    
      const getTitleAttr = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('title');
        return (v || '').trim();
      };
    
      const getLabelledByText = (el) => {
        if (!el || !el.getAttribute) return '';
        const ids = (el.getAttribute('aria-labelledby') || '').trim();
        if (!ids) return '';
        const parts = ids.split(/\s+/).filter(Boolean);
        const texts = [];
        for (const idref of parts) {
          const ref = safeRoot.getElementById ? safeRoot.getElementById(idref) : document.getElementById(idref);
          if (ref && ref.textContent) {
            const t = ref.textContent.trim();
            if (t) texts.push(t);
          }
        }
        return texts.join(' ').trim();
      };
    
      const isHiddenFromAT = (el) => {
        if (!el || !el.getAttribute) return false;
        const ariaHidden = (el.getAttribute('aria-hidden') || '').toLowerCase();
        return ariaHidden === 'true';
      };
    
    
      const inputs = query('input').filter((el) => {
        if (!el || !el.getAttribute || !el.tagName) return false;
        if (isHiddenFromAT(el)) return false;
        const t = (el.getAttribute('type') || '').toLowerCase();
        return t === 'image';
      });
    
      if (!inputs.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'serious',
          occurrences: []
        };
      }
    
      const occurrencesFail = [];
    
      for (const input of inputs) {
        const alt = (input.getAttribute('alt') || '').trim();
        const name =
            getAriaLabel(input) ||
            getLabelledByText(input) ||
            alt ||
            getTitleAttr(input);
    
        if (!name) {
          let selector = 'html';
          try { selector = buildSimpleSelector(input); } catch {}
          const html = getOuterHtmlSnippet(input);
    
          occurrencesFail.push({
            selector,
            html,
            summary: 'Image input has no accessible name.',
            hint: 'Provide a non-empty alt attribute, aria-label/aria-labelledby, or another accessible naming mechanism for the image button.'
          });
        }
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'serious',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    
    },
    "a11yCore-links-target-blank-noopener": function runInPage(ctx) {
      const { document, root, helpers, rule } = ctx;
    
      const queryAll = helpers && helpers.queryAll ? helpers.queryAll : (sel) => {
        try {
          return Array.from((root || document).querySelectorAll(sel));
        } catch {
          return [];
        }
      };
      const getOuterHtmlSnippet = helpers && helpers.getOuterHtmlSnippet
          ? helpers.getOuterHtmlSnippet
          : (el) => (el && el.outerHTML) || '';
      const buildSimpleSelector = helpers && helpers.buildSimpleSelector
          ? helpers.buildSimpleSelector
          : ((el) => {
            if (!el || typeof el !== 'object') return 'html';
            const tag = el.tagName ? el.tagName.toLowerCase() : 'html';
            return tag;
          });
    
      const links = queryAll('a[target="_blank"]');
    
      if (!links.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'minor',   // ✅ use rule
          occurrences: []
        };
      }
    
      const failing = [];
    
      for (const a of links) {
        const rel = (a.getAttribute && a.getAttribute('rel')) || '';
        const relParts = rel.split(/\s+/).filter(Boolean).map((s) => s.toLowerCase());
        const hasNoopener = relParts.includes('noopener') || relParts.includes('noreferrer');
    
        if (!hasNoopener) {
          failing.push({
            selector: buildSimpleSelector(a, 'a'),
            html: getOuterHtmlSnippet(a),
            summary: 'Link opens in a new tab but does not use rel="noopener" or rel="noreferrer".'
          });
        }
      }
    
      if (!failing.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'pass',
          severity: rule.defaultSeverity || 'minor',   // ✅ use rule
          occurrences: []
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'fail',
        severity: rule.defaultSeverity || 'minor',     // ✅ use rule
        occurrences: failing
      };
    },
    "manual-review": function runInPage(ctx) {
      const { document, root, helpers, rule } = ctx;
    
      const getOuterHtmlSnippet = helpers && helpers.getOuterHtmlSnippet
          ? helpers.getOuterHtmlSnippet
          : (el) => (el && el.outerHTML) || '';
    
      const contextSelector = ctx.contextSelector || null;
    
      let rootEl = root || null;
    
      if (!rootEl) {
        if (contextSelector) {
          try {
            rootEl = document.querySelector(contextSelector);
          } catch {
            // invalid selector, fallback to full document
            rootEl = null;
          }
        }
        if (!rootEl) {
          rootEl = document.documentElement || document.body || document.querySelector('html');
        }
      }
    
      const fallbackRoot =
          rootEl ||
          document.documentElement ||
          document.body ||
          document.querySelector('html');
    
      const html = getOuterHtmlSnippet(fallbackRoot);
    
      return {
        ruleId: rule.ruleId,
        outcome: 'cantTell',
        severity: 'moderate',
        occurrences: [
          {
            selector: contextSelector || 'html',
            html,
            summary: 'Manual review required for keyboard navigation and focus order.'
          }
        ]
      };
    },
    "a11yCore-nontext-equivalent-alternative-manual": function runInPage(ctx) {
      // SAFETY: This function runs in the page context via serialization. Do not capture outer scope.
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot = root || document;
    
      const queryAll =
          helpers && helpers.queryAll
              ? helpers.queryAll
              : (sel) => {
                if (!safeRoot || !safeRoot.querySelectorAll) return [];
                try {
                  return Array.from(safeRoot.querySelectorAll(sel));
                } catch {
                  return [];
                }
              };
    
      const queryAllSmart =
          helpers && helpers.queryAllSmart
              ? helpers.queryAllSmart
              : null;
    
      const query =
          queryAllSmart
              ? (sel) => {
                try {
                  return Array.from(queryAllSmart(sel) || []);
                } catch {
                  return queryAll(sel);
                }
              }
              : queryAll;
    
      const getOuterHtmlSnippet =
          helpers && helpers.getOuterHtmlSnippet
              ? helpers.getOuterHtmlSnippet
              : (el) => {
                if (!el || typeof el !== 'object') return '';
                return el.outerHTML || '';
              };
    
      const buildSimpleSelector =
          helpers && helpers.buildSimpleSelector
              ? helpers.buildSimpleSelector
              : (el) => {
                if (!el || typeof el !== 'object') return 'html';
                const tag = (el.tagName || 'html').toLowerCase();
                const id = el.id ? `#${el.id}` : '';
                const cls = el.classList && el.classList.length
                    ? '.' + Array.from(el.classList).slice(0, 2).join('.')
                    : '';
                return `${tag}${id}${cls}` || 'html';
              };
    
      const getAriaLabel = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('aria-label');
        return (v || '').trim();
      };
    
      const getTitleAttr = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('title');
        return (v || '').trim();
      };
    
      const getLabelledByText = (el) => {
        if (!el || !el.getAttribute) return '';
        const ids = (el.getAttribute('aria-labelledby') || '').trim();
        if (!ids) return '';
        const parts = ids.split(/\s+/).filter(Boolean);
        const texts = [];
        for (const idref of parts) {
          const ref = safeRoot.getElementById ? safeRoot.getElementById(idref) : document.getElementById(idref);
          if (ref && ref.textContent) {
            const t = ref.textContent.trim();
            if (t) texts.push(t);
          }
        }
        return texts.join(' ').trim();
      };
    
      const isHiddenFromAT = (el) => {
        if (!el || !el.getAttribute) return false;
        const ariaHidden = (el.getAttribute('aria-hidden') || '').toLowerCase();
        return ariaHidden === 'true';
      };
    
    
      // Candidates where a text alternative mechanism exists, but equivalence must be verified by a human.
      const occurrences = [];
    
      const addOccurrence = (el, summary, hint) => {
        let selector = 'html';
        try { selector = buildSimpleSelector(el); } catch {}
        const html = getOuterHtmlSnippet(el);
        occurrences.push({ selector, html, summary, hint });
      };
    
      // <img> with alt attribute (including empty) — equivalence & decorative intent require judgment.
      for (const img of query('img').filter((el) => el && el.tagName && !isHiddenFromAT(el))) {
        if (img.hasAttribute && img.hasAttribute('alt')) {
          addOccurrence(
            img,
            'Verify the image text alternative is equivalent for its purpose.',
            'Confirm that alt text (or alt="") is appropriate: informative images need meaningful alt; decorative images should use alt=""; functional images should describe the function.'
          );
        }
      }
    
      // <svg> exposed as image with a name mechanism present.
      for (const svg of query('svg').filter((el) => {
        if (!el || !el.getAttribute || !el.tagName) return false;
        if (isHiddenFromAT(el)) return false;
        const role = (el.getAttribute('role') || '').toLowerCase();
        const hasLabel = !!getAriaLabel(el) || !!(el.getAttribute('aria-labelledby') || '').trim();
        if (!(role === 'img' || hasLabel)) return false;
        const titleEl = el.querySelector ? el.querySelector('title') : null;
        const titleText = titleEl && titleEl.textContent ? titleEl.textContent.trim() : '';
        const name = getAriaLabel(el) || getLabelledByText(el) || titleText || getTitleAttr(el);
        return !!name;
      })) {
        addOccurrence(
          svg,
          'Verify the SVG text alternative is equivalent for its purpose.',
          'Confirm the accessible name (<title>/aria-label/aria-labelledby) provides an equivalent alternative.'
        );
      }
    
      // <canvas> with fallback text or accessible name.
      for (const canvas of query('canvas').filter((el) => el && el.tagName && !isHiddenFromAT(el))) {
        const fallbackText = (canvas.textContent || '').trim();
        const name = getAriaLabel(canvas) || getLabelledByText(canvas) || getTitleAttr(canvas);
        if (fallbackText || name) {
          addOccurrence(
            canvas,
            'Verify the canvas text alternative is equivalent for its purpose.',
            'Confirm fallback text or accessible name conveys equivalent information. Complex graphics may need a longer description elsewhere.'
          );
        }
      }
    
      // <area href> with alt.
      for (const area of query('area[href]').filter((el) => el && el.tagName && !isHiddenFromAT(el))) {
        const alt = (area.getAttribute && area.getAttribute('alt') || '').trim();
        if (alt) {
          addOccurrence(
            area,
            'Verify the image map area alt text is equivalent for its purpose.',
            'Confirm the alt text describes the purpose/destination of the hotspot.'
          );
        }
      }
    
      // <input type="image"> with naming mechanism.
      for (const input of query('input').filter((el) => {
        if (!el || !el.getAttribute || !el.tagName) return false;
        if (isHiddenFromAT(el)) return false;
        const t = (el.getAttribute('type') || '').toLowerCase();
        return t === 'image';
      })) {
        const alt = (input.getAttribute('alt') || '').trim();
        const name = getAriaLabel(input) || getLabelledByText(input) || alt || getTitleAttr(input);
        if (name) {
          addOccurrence(
            input,
            'Verify the image input accessible name is equivalent for its purpose.',
            'Confirm the name describes the function of the image button.'
          );
        }
      }
    
      if (!occurrences.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'minor',
          occurrences: []
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'cantTell',
        severity: rule.defaultSeverity || 'minor',
        occurrences
      };
    
    },
    "a11yCore-svg-role-img-name": function runInPage(ctx) {
      // SAFETY: This function runs in the page context via serialization. Do not capture outer scope.
      const { document, root, helpers, rule } = ctx;
    
      const safeRoot = root || document;
    
      const queryAll =
          helpers && helpers.queryAll
              ? helpers.queryAll
              : (sel) => {
                if (!safeRoot || !safeRoot.querySelectorAll) return [];
                try {
                  return Array.from(safeRoot.querySelectorAll(sel));
                } catch {
                  return [];
                }
              };
    
      const queryAllSmart =
          helpers && helpers.queryAllSmart
              ? helpers.queryAllSmart
              : null;
    
      const query =
          queryAllSmart
              ? (sel) => {
                try {
                  return Array.from(queryAllSmart(sel) || []);
                } catch {
                  return queryAll(sel);
                }
              }
              : queryAll;
    
      const getOuterHtmlSnippet =
          helpers && helpers.getOuterHtmlSnippet
              ? helpers.getOuterHtmlSnippet
              : (el) => {
                if (!el || typeof el !== 'object') return '';
                return el.outerHTML || '';
              };
    
      const buildSimpleSelector =
          helpers && helpers.buildSimpleSelector
              ? helpers.buildSimpleSelector
              : (el) => {
                if (!el || typeof el !== 'object') return 'html';
                const tag = (el.tagName || 'html').toLowerCase();
                const id = el.id ? `#${el.id}` : '';
                const cls = el.classList && el.classList.length
                    ? '.' + Array.from(el.classList).slice(0, 2).join('.')
                    : '';
                return `${tag}${id}${cls}` || 'html';
              };
    
      const getAriaLabel = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('aria-label');
        return (v || '').trim();
      };
    
      const getTitleAttr = (el) => {
        if (!el || !el.getAttribute) return '';
        const v = el.getAttribute('title');
        return (v || '').trim();
      };
    
      const getLabelledByText = (el) => {
        if (!el || !el.getAttribute) return '';
        const ids = (el.getAttribute('aria-labelledby') || '').trim();
        if (!ids) return '';
        const parts = ids.split(/\s+/).filter(Boolean);
        const texts = [];
        for (const idref of parts) {
          const ref = safeRoot.getElementById ? safeRoot.getElementById(idref) : document.getElementById(idref);
          if (ref && ref.textContent) {
            const t = ref.textContent.trim();
            if (t) texts.push(t);
          }
        }
        return texts.join(' ').trim();
      };
    
      const isHiddenFromAT = (el) => {
        if (!el || !el.getAttribute) return false;
        const ariaHidden = (el.getAttribute('aria-hidden') || '').toLowerCase();
        return ariaHidden === 'true';
      };
    
    
      const svgs = query('svg').filter((el) => {
        if (!el || !el.getAttribute || !el.tagName) return false;
        if (isHiddenFromAT(el)) return false;
        const role = (el.getAttribute('role') || '').toLowerCase();
        const hasLabel = !!getAriaLabel(el) || !!(el.getAttribute('aria-labelledby') || '').trim();
        return role === 'img' || hasLabel;
      });
    
      if (!svgs.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'notApplicable',
          severity: rule.defaultSeverity || 'serious',
          occurrences: []
        };
      }
    
      const getTitleText = (svg) => {
        if (!svg || !svg.querySelector) return '';
        const t = svg.querySelector('title');
        return t && t.textContent ? t.textContent.trim() : '';
      };
    
      const occurrencesFail = [];
    
      for (const svg of svgs) {
        const name =
            getAriaLabel(svg) ||
            getLabelledByText(svg) ||
            getTitleText(svg) ||
            getTitleAttr(svg);
    
        if (!name) {
          let selector = 'html';
          try { selector = buildSimpleSelector(svg); } catch {}
          const html = getOuterHtmlSnippet(svg);
    
          occurrencesFail.push({
            selector,
            html,
            summary: 'SVG with role="img" has no accessible name.',
            hint: 'Provide an accessible name using <title>, aria-label, or aria-labelledby.'
          });
        }
      }
    
      if (occurrencesFail.length) {
        return {
          ruleId: rule.ruleId,
          outcome: 'fail',
          severity: rule.defaultSeverity || 'serious',
          occurrences: occurrencesFail
        };
      }
    
      return {
        ruleId: rule.ruleId,
        outcome: 'pass',
        severity: 'minor',
        occurrences: []
      };
    
    }
  };

  function normalizeRuleResult(def, raw) {
    const out = raw && typeof raw === 'object' ? { ...raw } : {};

    // rule id
    out.ruleId = out.ruleId || def.ruleId;

    // outcome
    if (!VALID_OUTCOMES.includes(out.outcome)) {
      out.outcome = 'cantTell';
    }

    // severity
    out.severity = out.severity || def.defaultSeverity || 'moderate';

    // confidence
    const defConfidence = def.defaultConfidence || 'medium';
    let conf = raw && raw.confidence;
    if (!VALID_CONFIDENCE.includes(conf)) {
      conf = defConfidence;
    }
    out.confidence = conf;

    // type (copied from definition, not from raw)
    out.type = def.type || 'automatic';

    // occurrences
    const occ = Array.isArray(out.occurrences) ? out.occurrences : [];
    out.occurrences = occ.map((item) => {
      const o = item && typeof item === 'object' ? { ...item } : {};
      if (typeof o.selector !== 'string') o.selector = '';
      if (typeof o.summary !== 'string') o.summary = '';
      if (typeof o.html !== 'string') o.html = '';
      return o;
    });

    // error, if any
    if (raw && raw.error) {
      out.error = String(raw.error);
    }

    return out;
  }

  const ctxSelector =
    (typeof contextSelector === 'string' && contextSelector.trim())
      ? contextSelector.trim()
      : null;

  const root =
    ctxSelector
      ? (document.querySelector(ctxSelector) ||
         document.documentElement ||
         document.body ||
         document.querySelector('html'))
      : (document.documentElement ||
         document.body ||
         document.querySelector('html'));

  // Shadow DOM support (open shadow roots only)
  // Default: false to avoid unexpected performance costs.
  const includeShadowDom = !!(engineOptions && engineOptions.includeShadowDom);

  const url = pageUrl || (document.location && document.location.href) || null;
  const title = document.title || null;
  const timestamp = new Date().toISOString();

  function ruleMatchesRunOnlyInPage(ruleTags, runOnlyArg) {
    if (!runOnlyArg || runOnlyArg.type !== 'tag') return true;
    const values = Array.isArray(runOnlyArg.values) ? runOnlyArg.values : [];
    if (!values.length) return true;
    const tags = Array.isArray(ruleTags) ? ruleTags : [];
    return tags.some((t) => values.includes(t));
  }

  function queryAll(sel) {
    if (!root) return [];
    try {
      return Array.from(root.querySelectorAll(sel));
    } catch {
      return [];
    }
  }

  // Deep query that traverses open shadow roots.
  // Note: closed shadow roots cannot be accessed by design.
  function queryAllDeep(sel) {
    if (!root) return [];
    const results = [];
    const seen = new Set();

    function pushAll(node) {
      if (!node || !node.querySelectorAll) return;
      let els = [];
      try {
        els = Array.from(node.querySelectorAll(sel));
      } catch {
        els = [];
      }
      for (const el of els) {
        if (el && !seen.has(el)) {
          seen.add(el);
          results.push(el);
        }
      }
    }

    function walk(node) {
      if (!node) return;

      pushAll(node);

      // Traverse hosts in this tree and recurse into open shadow roots
      let all = [];
      try {
        all = node.querySelectorAll ? Array.from(node.querySelectorAll('*')) : [];
      } catch {
        all = [];
      }

      for (const el of all) {
        if (el && el.shadowRoot) {
          walk(el.shadowRoot);
        }
      }
    }

    walk(root);
    return results;
  }

  // Convenience: select the query strategy based on engineOptions.includeShadowDom
  function queryAllSmart(sel) {
    return includeShadowDom ? queryAllDeep(sel) : queryAll(sel);
  }

  function getOuterHtmlSnippet(el) {
    if (!el || typeof el !== 'object') return '';
    try {
      const html = el.outerHTML || '';
      if (html.length > 2000) return html.slice(0, 2000) + '…';
      return html;
    } catch {
      return '';
    }
  }

  function buildSimpleSelector(el, fallbackTag) {
    try {
      if (!el || typeof el !== 'object') return fallbackTag || 'html';
      const tag = el.tagName ? el.tagName.toLowerCase() : (fallbackTag || 'html');
      const id = el.getAttribute && el.getAttribute('id');
      if (id && id.trim()) return tag + '#' + id.trim();
      const classes = (el.getAttribute && el.getAttribute('class')) || '';
      const cls = classes.split(/\s+/).filter(Boolean);
      if (cls.length) return tag + '.' + cls[0];
      const name = el.getAttribute && el.getAttribute('name');
      if (name && name.trim()) return tag + '[name="' + name.trim() + '"]';
      return tag;
    } catch {
      return fallbackTag || 'html';
    }
  }

  function hasAccessibleName(el) {
    if (!el || typeof el !== 'object') return false;

    const ariaLabel = el.getAttribute && el.getAttribute('aria-label');
    if (ariaLabel && ariaLabel.trim()) return true;

    const labelledby = el.getAttribute && el.getAttribute('aria-labelledby');
    if (labelledby && labelledby.trim()) {
      const ids = labelledby.trim().split(/\s+/);
      for (const id of ids) {
        const ref = document.getElementById(id);
        if (ref && typeof ref.textContent === 'string' && ref.textContent.trim()) return true;
      }
    }

    const id = el.getAttribute && el.getAttribute('id');
    if (id && document.querySelector) {
      try {
        const escapedId = (window.CSS && window.CSS.escape) ? window.CSS.escape(id) : id;
        const explicitLabel = document.querySelector('label[for="' + escapedId + '"]');
        if (explicitLabel && explicitLabel.textContent && explicitLabel.textContent.trim()) return true;
      } catch {
        try {
          const explicitLabel = document.querySelector('label[for="' + id + '"]');
          if (explicitLabel && explicitLabel.textContent && explicitLabel.textContent.trim()) return true;
        } catch {
        }
      }
    }

    if (el.closest) {
      const wrapLabel = el.closest('label');
      if (wrapLabel && wrapLabel.textContent && wrapLabel.textContent.trim()) return true;
    }

    return false;
  }

  const sharedHelpers = {
    // Back-compat: keep queryAll behaving as before (light DOM only).
    // New: queryAllDeep + queryAllSmart for Shadow DOM scanning.
    queryAll,
    queryAllDeep,
    queryAllSmart,
    getOuterHtmlSnippet,
    buildSimpleSelector,
    hasAccessibleName
  };

  const rulesResults = [];

  for (const def of RULE_DEFS) {
    if (!ruleMatchesRunOnlyInPage(def.tags, runOnly)) continue;
    const impl = RULE_IMPLS[def.ruleId];
    if (typeof impl !== 'function') continue;

    const ruleConfig =
      engineOptions && engineOptions.rules && engineOptions.rules[def.ruleId]
        ? engineOptions.rules[def.ruleId]
        : null;

    const ctx = {
      document,
      window,
      root,
      rule: def,
      config: ruleConfig,
      helpers: sharedHelpers,
      engineTag: ENGINE_TAG,
      contextSelector: ctxSelector
    };

    let result;
    try {
      result = impl(ctx);
    } catch (err) {
      result = {
        ruleId: def.ruleId,
        outcome: 'cantTell',
        severity: def.defaultSeverity || 'moderate',
        occurrences: [],
        error: String(err && err.message ? err.message : err)
      };
    }

    if (!result || typeof result !== 'object') continue;

    const normalized = normalizeRuleResult(def, result);
    rulesResults.push(normalized);
  }

  return {
    url,
    title,
    timestamp,
    contextSelector: ctxSelector,
    rules: rulesResults
  };
}

module.exports = {
  ENGINE_TAG,
  getRuleDefById,
  getRulesCatalog,
  getRulesForRunOnly,
  runa11yCoreInPage
};
