const { run, ids, core } = require('./h');
const html = '<html lang="en"><head><title>t</title></head><body><main><img src="a.png"><button></button></main></body></html>';
const all = run(html).checksResults.length;
console.log('all', all);
const t = (label, ro, eo={}) => { try { const r = run(html, null, eo, ro); console.log(label, r.checksResults.length, r.checksResults.length<6? ids(r):''); } catch(e) { console.log(label, 'THROW', e.code, e.message); } };
t('tag string values', { type:'tag', values:'wcag2a' });
t('tag array values', { type:'tag', values:['wcag2a'] });
t('tag+excludeTags', { type:'tag', values:['wcag2a'], excludeTags:['wcag111'] });
t('rule+exclude', { type:'rule', values:['img-alt-present','button-name-present'], excludeRuleIds:['button-name-present'] });
t('type tag no values', { type:'tag' });
t('type rule no values', { type:'rule' });
t('typo+includeMode', { includeRuleId:['img-alt-present'], includeMode:'or' });
t('typo+excludeTags', { includeRuleId:['img-alt-present'], excludeTags:['best-practice'] });
t('composite prefixed', ['a11ycore-img-alt-present']);
t('values typo', { type:'tag', values:['wcag2aaaa'] });
t('values string typo', { type:'tag', values:'wcag2aaaa' });
t('number in array', [1]);
t('nested array', [['img-alt-present']]);
t('__proto__', ['__proto__']);
t('constructor', ['constructor']);
t('toString', { includeRuleIds:['toString'] });
t('hasOwnProperty tag', { tags:['hasOwnProperty'] });
t('includeTestIds typo', { includeTestIds:['nope'] });
t('excludeOnly unknown', { excludeRuleIds:['nope'] });
t('empty obj', {});
t('null-proto', Object.assign(Object.create(null), {includeRuleIds:['img-alt-present']}));
t('Map', new Map());
t('Set', new Set(['img-alt-present']));
t('Date', new Date());
t('function', function(){});
t('eo rules include string typo', null, { rules: { include: 'nope' } });
t('eo rules string', null, { rules: 'img-alt-present' });
t('eo tags string', null, { tags: 'wcag2a' });
t('eo tags array', null, { tags: ['wcag2a'] });
t('eo rules array', null, { rules: ['img-alt-present'] });
t('eo tests typo', null, { tests: { include: 'nope' } });
