const { run, core } = require('./h');
const html = '<html lang="en"><head><title>t</title></head><body><main><img src="a.png"><div id="d"></div><div id="d"></div></main></body></html>';
const t = (label, eo, ro=null) => { try { const r = run(html, null, eo, ro); console.log(label, 'n=', r.checksResults.length, 'r=', r.rulesResults.length, JSON.stringify({p: r.engine.profile, v: r.engine.wcagVersion, m: r.engine.mappings, o: r.engine.optInRules})); } catch (e) { console.log(label, 'THROW', e.message); } };
t('none', {});
t('wcag22-aa', { profile: 'wcag22-aa' });
t('WCAG22-AA ', { profile: ' WCAG22-AA ' });
t('constructor', { profile: 'constructor' });
t('__proto__', { profile: '__proto__' });
t('toString', { profile: 'toString' });
t('hasOwnProperty', { profile: 'hasOwnProperty' });
t('en v3', { profile: 'en301549-v3.2.1' });
t('en v3 + wcagVersion 2.2', { profile: 'en301549-v3.2.1', wcagVersion: '2.2' });
t('section508 + excludeTags', { profile: 'section508' }, { excludeTags: ['best-practice'] });
t('section508 + tags', { profile: 'section508' }, { tags: ['wcag2a'] });
t('optIn all', { optInRules: 'all' });
t('optIn true', { optInRules: true });
t('mappings __proto__', { mappings: ['__proto__', 'constructor', 'toString:x'] });
t('mappings en301549:v4.1.1', { mappings: 'EN301549:v4.1.1' });
t('wcagVersion 2.1 number', { wcagVersion: 2.1 });
t('profile array', { profile: ['wcag22-aa'] });
const cat = core.getChecksCatalog({ profile: 'section508' }); console.log('catalog section508', cat.length);
console.log('getChecksForRunOnly', core.getChecksForRunOnly(null, { profile: 'section508' }).length);
console.log('rulesCatalog', core.getRulesCatalog({ profile: 'section508' }).length, core.getRulesCatalog({}).length);
