module.exports = {
  arrMap: () => { const o = Array.prototype.map; Array.prototype.map = function (f, t) { return o.call(this, f, t).concat([]); }; },
  arrMapBroken: () => { Array.prototype.map = function () { return []; }; },
  arrFilterBroken: () => { Array.prototype.filter = function () { return []; }; },
  arrFromBroken: () => { Array.from = function (x) { return []; }; },
  arrIncludes: () => { Array.prototype.includes = function () { return false; }; },
  arrForEachEnum: () => { Array.prototype.myExtra = function () {}; Object.prototype.polluted = 'x'; },
  objKeys: () => { Object.keys = function () { return []; }; },
  objEntries: () => { Object.entries = function () { return []; }; },
  objAssign: () => { Object.assign = function (t) { return t; }; },
  jsonStringify: () => { JSON.stringify = function () { return '{}'; }; },
  jsonParse: () => { JSON.parse = function () { return {}; }; },
  qsa: () => { Element.prototype.querySelectorAll = function () { return []; }; Document.prototype.querySelectorAll = function () { return []; }; },
  qs: () => { document.querySelector = function () { return null; }; },
  gcs: () => { window.getComputedStyle = function () { throw new Error('nope'); }; },
  gcsNull: () => { window.getComputedStyle = function () { return null; }; },
  mapBroken: () => { const M = Map; window.Map = class extends M { get() { return undefined; } }; },
  mapPolyfill: () => { Map.prototype.get = function () { return undefined; }; },
  setHas: () => { Set.prototype.has = function () { return false; }; },
  weakMap: () => { WeakMap.prototype.get = function () { return undefined; }; },
  symIter: () => { Array.prototype[Symbol.iterator] = function* () {}; },
  nodeListIter: () => { NodeList.prototype[Symbol.iterator] = function* () {}; NodeList.prototype.forEach = function () {}; },
  contains: () => { Node.prototype.contains = function () { return false; }; },
  trim: () => { String.prototype.trim = function () { return this + ' '; }; },
  toLower: () => { String.prototype.toLowerCase = function () { return String(this); }; },
  replace: () => { String.prototype.replace = function () { return String(this); }; },
  split: () => { String.prototype.split = function () { return [String(this)]; }; },
  regexpTest: () => { RegExp.prototype.test = function () { return false; }; },
  getAttr: () => { const o = Element.prototype.getAttribute; Element.prototype.getAttribute = function (n) { return o.call(this, n); }; },
  getAttrBroken: () => { Element.prototype.getAttribute = function () { return null; }; },
  matches: () => { Element.prototype.matches = function () { return false; }; },
  closest: () => { Element.prototype.closest = function () { return null; }; },
  getById: () => { document.getElementById = function () { return null; }; },
  promise: () => { window.Promise = function () { throw new Error('p'); }; },
  mathMax: () => { Math.max = function () { return 0; }; Math.min = function () { return 0; }; },
  numberParse: () => { window.parseFloat = function () { return NaN; }; Number.parseFloat = window.parseFloat; },
  perfNow: () => { performance.now = function () { throw new Error('x'); }; },
  dateNow: () => { Date.now = function () { return NaN; }; },
  textContent: () => { Object.defineProperty(Node.prototype, 'textContent', { get() { return ''; } }); },
  frozen: () => { Object.freeze(Object.prototype); Object.freeze(Array.prototype); Object.freeze(Map.prototype); Object.freeze(Element.prototype); Object.freeze(Node.prototype); },
  elementFromPoint: () => { document.elementFromPoint = function () { return null; }; document.elementsFromPoint = function () { return []; }; },
  getBCR: () => { Element.prototype.getBoundingClientRect = function () { throw new Error('bcr'); }; },
  getClientRects: () => { Element.prototype.getClientRects = function () { return []; }; },
  createTreeWalker: () => { document.createTreeWalker = function () { throw new Error('tw'); }; },
  focus: () => { HTMLElement.prototype.focus = function () { throw new Error('f'); }; },
  activeElement: () => { Object.defineProperty(Document.prototype, 'activeElement', { get() { throw new Error('ae'); } }); },
  cssEscape: () => { CSS.escape = function (s) { return s; }; },
  cssNull: () => { window.CSS = undefined; },
  attachShadowClosed: () => { const o = Element.prototype.attachShadow; Element.prototype.attachShadow = function (i) { return o.call(this, { ...i, mode: 'closed' }); }; },
  customElThrows: () => { customElements.define('my-el', class extends HTMLElement { get tagName() { throw new Error('t'); } get id() { throw new Error('i'); } getAttribute() { throw new Error('g'); } get shadowRoot() { throw new Error('s'); } }); },
  styleSheets: () => { Object.defineProperty(Document.prototype, 'styleSheets', { get() { throw new Error('ss'); } }); },
  checkVis: () => { Element.prototype.checkVisibility = function () { return false; }; },
  arrayCtor: () => { window.Array = function () { throw new Error('A'); }; },
  objectCreate: () => { Object.create = function () { return {}; }; },
  stringCtor: () => { window.String = function (x) { return 'S'; }; },
  windowSelf: () => { window.window2 = 1; Object.defineProperty(window, 'self', { value: null }); },
  setTimeoutBroken: () => { window.setTimeout = function () { throw new Error('st'); }; },
  mutationObserver: () => { new MutationObserver(() => { const d = document.createElement('div'); d.textContent = 'm'; if (document.body.children.length < 200) document.body.appendChild(d); }).observe(document.documentElement, { attributes: true, childList: true, subtree: true }); },
  focusHandlerMutates: () => { document.addEventListener('focusin', (e) => { const b = document.createElement('button'); document.body.appendChild(b); }, true); },
  focusHandlerRemoves: () => { document.addEventListener('focusin', (e) => { const t = e.target; if (t && t.parentNode && t.tagName !== 'BODY') t.parentNode.removeChild(t); }, true); },
};
